; Hangul syllable and jamo mappings supported by the imported Gold font.
; Each glyph is encoded as escape, font bank, and glyph index.
charmap "간", HANGUL_POC_ESCAPE, $01, $03
charmap "갇", HANGUL_POC_ESCAPE, $01, $04
charmap "갈", HANGUL_POC_ESCAPE, $01, $05
charmap "갉", HANGUL_POC_ESCAPE, $01, $06
charmap "갊", HANGUL_POC_ESCAPE, $01, $07
charmap "감", HANGUL_POC_ESCAPE, $01, $08
charmap "갑", HANGUL_POC_ESCAPE, $01, $09
charmap "값", HANGUL_POC_ESCAPE, $01, $0a
charmap "갓", HANGUL_POC_ESCAPE, $01, $0b
charmap "갔", HANGUL_POC_ESCAPE, $01, $0c
charmap "강", HANGUL_POC_ESCAPE, $01, $0d
charmap "갖", HANGUL_POC_ESCAPE, $01, $0e
charmap "갗", HANGUL_POC_ESCAPE, $01, $0f
charmap "같", HANGUL_POC_ESCAPE, $01, $10
charmap "갚", HANGUL_POC_ESCAPE, $01, $11
charmap "갛", HANGUL_POC_ESCAPE, $01, $12
charmap "개", HANGUL_POC_ESCAPE, $01, $13
charmap "객", HANGUL_POC_ESCAPE, $01, $14
charmap "갠", HANGUL_POC_ESCAPE, $01, $15
charmap "갤", HANGUL_POC_ESCAPE, $01, $16
charmap "갬", HANGUL_POC_ESCAPE, $01, $17
charmap "갭", HANGUL_POC_ESCAPE, $01, $18
charmap "갯", HANGUL_POC_ESCAPE, $01, $19
charmap "갰", HANGUL_POC_ESCAPE, $01, $1a
charmap "갱", HANGUL_POC_ESCAPE, $01, $1b
charmap "갸", HANGUL_POC_ESCAPE, $01, $1c
charmap "갹", HANGUL_POC_ESCAPE, $01, $1d
charmap "갼", HANGUL_POC_ESCAPE, $01, $1e
charmap "걀", HANGUL_POC_ESCAPE, $01, $1f
charmap "걋", HANGUL_POC_ESCAPE, $01, $20
charmap "걍", HANGUL_POC_ESCAPE, $01, $21
charmap "걔", HANGUL_POC_ESCAPE, $01, $22
charmap "걘", HANGUL_POC_ESCAPE, $01, $23
charmap "걜", HANGUL_POC_ESCAPE, $01, $24
charmap "거", HANGUL_POC_ESCAPE, $01, $25
charmap "걱", HANGUL_POC_ESCAPE, $01, $26
charmap "건", HANGUL_POC_ESCAPE, $01, $27
charmap "걷", HANGUL_POC_ESCAPE, $01, $28
charmap "걸", HANGUL_POC_ESCAPE, $01, $29
charmap "걺", HANGUL_POC_ESCAPE, $01, $2a
charmap "검", HANGUL_POC_ESCAPE, $01, $2b
charmap "겁", HANGUL_POC_ESCAPE, $01, $2c
charmap "것", HANGUL_POC_ESCAPE, $01, $2d
charmap "겄", HANGUL_POC_ESCAPE, $01, $2e
charmap "겅", HANGUL_POC_ESCAPE, $01, $2f
charmap "겆", HANGUL_POC_ESCAPE, $01, $30
charmap "겉", HANGUL_POC_ESCAPE, $01, $31
charmap "겊", HANGUL_POC_ESCAPE, $01, $32
charmap "겋", HANGUL_POC_ESCAPE, $01, $33
charmap "게", HANGUL_POC_ESCAPE, $01, $34
charmap "겐", HANGUL_POC_ESCAPE, $01, $35
charmap "겔", HANGUL_POC_ESCAPE, $01, $36
charmap "겜", HANGUL_POC_ESCAPE, $01, $37
charmap "겝", HANGUL_POC_ESCAPE, $01, $38
charmap "겟", HANGUL_POC_ESCAPE, $01, $39
charmap "겠", HANGUL_POC_ESCAPE, $01, $3a
charmap "겡", HANGUL_POC_ESCAPE, $01, $3b
charmap "겨", HANGUL_POC_ESCAPE, $01, $3c
charmap "격", HANGUL_POC_ESCAPE, $01, $3d
charmap "겪", HANGUL_POC_ESCAPE, $01, $3e
charmap "견", HANGUL_POC_ESCAPE, $01, $3f
charmap "겯", HANGUL_POC_ESCAPE, $01, $40
charmap "결", HANGUL_POC_ESCAPE, $01, $41
charmap "겹", HANGUL_POC_ESCAPE, $01, $42
charmap "겸", HANGUL_POC_ESCAPE, $01, $43
charmap "겻", HANGUL_POC_ESCAPE, $01, $44
charmap "겼", HANGUL_POC_ESCAPE, $01, $45
charmap "경", HANGUL_POC_ESCAPE, $01, $46
charmap "곁", HANGUL_POC_ESCAPE, $01, $47
charmap "계", HANGUL_POC_ESCAPE, $01, $48
charmap "곈", HANGUL_POC_ESCAPE, $01, $49
charmap "곌", HANGUL_POC_ESCAPE, $01, $4a
charmap "곕", HANGUL_POC_ESCAPE, $01, $4b
charmap "곗", HANGUL_POC_ESCAPE, $01, $4c
charmap "고", HANGUL_POC_ESCAPE, $01, $4d
charmap "곡", HANGUL_POC_ESCAPE, $01, $4e
charmap "곤", HANGUL_POC_ESCAPE, $01, $4f
charmap "곧", HANGUL_POC_ESCAPE, $01, $60
charmap "골", HANGUL_POC_ESCAPE, $01, $61
charmap "곪", HANGUL_POC_ESCAPE, $01, $62
charmap "곬", HANGUL_POC_ESCAPE, $01, $63
charmap "곯", HANGUL_POC_ESCAPE, $01, $64
charmap "곰", HANGUL_POC_ESCAPE, $01, $65
charmap "곱", HANGUL_POC_ESCAPE, $01, $66
charmap "곳", HANGUL_POC_ESCAPE, $01, $67
charmap "공", HANGUL_POC_ESCAPE, $01, $68
charmap "곶", HANGUL_POC_ESCAPE, $01, $69
charmap "과", HANGUL_POC_ESCAPE, $01, $6a
charmap "곽", HANGUL_POC_ESCAPE, $01, $6b
charmap "관", HANGUL_POC_ESCAPE, $01, $6c
charmap "괄", HANGUL_POC_ESCAPE, $01, $6d
charmap "괆", HANGUL_POC_ESCAPE, $01, $6e
charmap "괌", HANGUL_POC_ESCAPE, $01, $71
charmap "괍", HANGUL_POC_ESCAPE, $01, $72
charmap "괏", HANGUL_POC_ESCAPE, $01, $73
charmap "광", HANGUL_POC_ESCAPE, $01, $74
charmap "괘", HANGUL_POC_ESCAPE, $01, $75
charmap "괜", HANGUL_POC_ESCAPE, $01, $76
charmap "괠", HANGUL_POC_ESCAPE, $01, $77
charmap "괩", HANGUL_POC_ESCAPE, $01, $78
charmap "괬", HANGUL_POC_ESCAPE, $01, $79
charmap "괭", HANGUL_POC_ESCAPE, $01, $7a
charmap "괴", HANGUL_POC_ESCAPE, $01, $7b
charmap "괵", HANGUL_POC_ESCAPE, $01, $7c
charmap "괸", HANGUL_POC_ESCAPE, $01, $7d
charmap "괼", HANGUL_POC_ESCAPE, $01, $7e
charmap "괻", HANGUL_POC_ESCAPE, $01, $7f
charmap "굅", HANGUL_POC_ESCAPE, $01, $80
charmap "굇", HANGUL_POC_ESCAPE, $01, $81
charmap "굉", HANGUL_POC_ESCAPE, $01, $82
charmap "교", HANGUL_POC_ESCAPE, $01, $83
charmap "굔", HANGUL_POC_ESCAPE, $01, $84
charmap "굘", HANGUL_POC_ESCAPE, $01, $85
charmap "굡", HANGUL_POC_ESCAPE, $01, $86
charmap "굣", HANGUL_POC_ESCAPE, $01, $87
charmap "구", HANGUL_POC_ESCAPE, $01, $88
charmap "국", HANGUL_POC_ESCAPE, $01, $89
charmap "군", HANGUL_POC_ESCAPE, $01, $8a
charmap "굳", HANGUL_POC_ESCAPE, $01, $8b
charmap "굴", HANGUL_POC_ESCAPE, $01, $8c
charmap "굵", HANGUL_POC_ESCAPE, $01, $8d
charmap "굶", HANGUL_POC_ESCAPE, $01, $8e
charmap "굻", HANGUL_POC_ESCAPE, $01, $8f
charmap "굼", HANGUL_POC_ESCAPE, $01, $90
charmap "굽", HANGUL_POC_ESCAPE, $01, $91
charmap "굿", HANGUL_POC_ESCAPE, $01, $92
charmap "궁", HANGUL_POC_ESCAPE, $01, $93
charmap "궂", HANGUL_POC_ESCAPE, $01, $94
charmap "궈", HANGUL_POC_ESCAPE, $01, $95
charmap "궉", HANGUL_POC_ESCAPE, $01, $96
charmap "권", HANGUL_POC_ESCAPE, $01, $97
charmap "궐", HANGUL_POC_ESCAPE, $01, $98
charmap "궜", HANGUL_POC_ESCAPE, $01, $99
charmap "궝", HANGUL_POC_ESCAPE, $01, $9a
charmap "궤", HANGUL_POC_ESCAPE, $01, $9b
charmap "궷", HANGUL_POC_ESCAPE, $01, $9c
charmap "귀", HANGUL_POC_ESCAPE, $01, $9d
charmap "귁", HANGUL_POC_ESCAPE, $01, $9e
charmap "귄", HANGUL_POC_ESCAPE, $01, $9f
charmap "귈", HANGUL_POC_ESCAPE, $01, $a0
charmap "귐", HANGUL_POC_ESCAPE, $01, $a1
charmap "귑", HANGUL_POC_ESCAPE, $01, $a2
charmap "귓", HANGUL_POC_ESCAPE, $01, $a3
charmap "규", HANGUL_POC_ESCAPE, $01, $a4
charmap "균", HANGUL_POC_ESCAPE, $01, $a5
charmap "귤", HANGUL_POC_ESCAPE, $01, $a6
charmap "그", HANGUL_POC_ESCAPE, $01, $a7
charmap "극", HANGUL_POC_ESCAPE, $01, $a8
charmap "근", HANGUL_POC_ESCAPE, $01, $a9
charmap "귿", HANGUL_POC_ESCAPE, $01, $aa
charmap "긁", HANGUL_POC_ESCAPE, $01, $ac
charmap "금", HANGUL_POC_ESCAPE, $01, $ad
charmap "급", HANGUL_POC_ESCAPE, $01, $ae
charmap "긋", HANGUL_POC_ESCAPE, $01, $af
charmap "긍", HANGUL_POC_ESCAPE, $01, $b0
charmap "긔", HANGUL_POC_ESCAPE, $01, $b1
charmap "기", HANGUL_POC_ESCAPE, $01, $b2
charmap "긱", HANGUL_POC_ESCAPE, $01, $b3
charmap "긴", HANGUL_POC_ESCAPE, $01, $b4
charmap "긷", HANGUL_POC_ESCAPE, $01, $b5
charmap "길", HANGUL_POC_ESCAPE, $01, $b6
charmap "긺", HANGUL_POC_ESCAPE, $01, $b7
charmap "김", HANGUL_POC_ESCAPE, $01, $b8
charmap "깁", HANGUL_POC_ESCAPE, $01, $b9
charmap "깃", HANGUL_POC_ESCAPE, $01, $ba
charmap "깅", HANGUL_POC_ESCAPE, $01, $bb
charmap "깆", HANGUL_POC_ESCAPE, $01, $bc
charmap "깊", HANGUL_POC_ESCAPE, $01, $bd
charmap "까", HANGUL_POC_ESCAPE, $01, $be
charmap "깍", HANGUL_POC_ESCAPE, $01, $bf
charmap "깎", HANGUL_POC_ESCAPE, $01, $c0
charmap "깐", HANGUL_POC_ESCAPE, $01, $c1
charmap "깔", HANGUL_POC_ESCAPE, $01, $c2
charmap "깖", HANGUL_POC_ESCAPE, $01, $c3
charmap "깜", HANGUL_POC_ESCAPE, $01, $c4
charmap "깝", HANGUL_POC_ESCAPE, $01, $c5
charmap "깟", HANGUL_POC_ESCAPE, $01, $c6
charmap "깠", HANGUL_POC_ESCAPE, $01, $c7
charmap "깡", HANGUL_POC_ESCAPE, $01, $c8
charmap "깥", HANGUL_POC_ESCAPE, $01, $c9
charmap "깨", HANGUL_POC_ESCAPE, $01, $ca
charmap "깩", HANGUL_POC_ESCAPE, $01, $cb
charmap "깬", HANGUL_POC_ESCAPE, $01, $cc
charmap "깰", HANGUL_POC_ESCAPE, $01, $cd
charmap "깸", HANGUL_POC_ESCAPE, $01, $ce
charmap "깹", HANGUL_POC_ESCAPE, $01, $d1
charmap "깻", HANGUL_POC_ESCAPE, $01, $d2
charmap "깼", HANGUL_POC_ESCAPE, $01, $d3
charmap "깽", HANGUL_POC_ESCAPE, $01, $d4
charmap "꺄", HANGUL_POC_ESCAPE, $01, $d5
charmap "꺅", HANGUL_POC_ESCAPE, $01, $d6
charmap "꺌", HANGUL_POC_ESCAPE, $01, $d7
charmap "꺼", HANGUL_POC_ESCAPE, $01, $d8
charmap "꺽", HANGUL_POC_ESCAPE, $01, $d9
charmap "꺾", HANGUL_POC_ESCAPE, $01, $da
charmap "껀", HANGUL_POC_ESCAPE, $01, $db
charmap "껄", HANGUL_POC_ESCAPE, $01, $dc
charmap "껌", HANGUL_POC_ESCAPE, $01, $dd
charmap "껍", HANGUL_POC_ESCAPE, $01, $de
charmap "껏", HANGUL_POC_ESCAPE, $01, $df
charmap "껐", HANGUL_POC_ESCAPE, $01, $e0
charmap "껑", HANGUL_POC_ESCAPE, $01, $e1
charmap "께", HANGUL_POC_ESCAPE, $01, $e2
charmap "껙", HANGUL_POC_ESCAPE, $01, $e3
charmap "껜", HANGUL_POC_ESCAPE, $01, $e4
charmap "껨", HANGUL_POC_ESCAPE, $01, $e5
charmap "껫", HANGUL_POC_ESCAPE, $01, $e6
charmap "껭", HANGUL_POC_ESCAPE, $01, $e7
charmap "껴", HANGUL_POC_ESCAPE, $01, $e8
charmap "껸", HANGUL_POC_ESCAPE, $01, $e9
charmap "껼", HANGUL_POC_ESCAPE, $01, $ea
charmap "꼇", HANGUL_POC_ESCAPE, $01, $eb
charmap "꼈", HANGUL_POC_ESCAPE, $01, $ec
charmap "꼍", HANGUL_POC_ESCAPE, $01, $ed
charmap "꼐", HANGUL_POC_ESCAPE, $01, $ee
charmap "꼬", HANGUL_POC_ESCAPE, $01, $ef
charmap "꼭", HANGUL_POC_ESCAPE, $01, $f0
charmap "꼰", HANGUL_POC_ESCAPE, $01, $f1
charmap "꼲", HANGUL_POC_ESCAPE, $01, $f2
charmap "꼴", HANGUL_POC_ESCAPE, $01, $f3
charmap "꼼", HANGUL_POC_ESCAPE, $01, $f4
charmap "꼽", HANGUL_POC_ESCAPE, $01, $f5
charmap "꼿", HANGUL_POC_ESCAPE, $01, $f6
charmap "꽁", HANGUL_POC_ESCAPE, $01, $f7
charmap "꽂", HANGUL_POC_ESCAPE, $01, $f8
charmap "꽃", HANGUL_POC_ESCAPE, $01, $f9
charmap "꽈", HANGUL_POC_ESCAPE, $01, $fa
charmap "꽉", HANGUL_POC_ESCAPE, $01, $fb
charmap "꽐", HANGUL_POC_ESCAPE, $01, $fc
charmap "꽜", HANGUL_POC_ESCAPE, $01, $fd
charmap "꽝", HANGUL_POC_ESCAPE, $01, $fe
charmap "꽤", HANGUL_POC_ESCAPE, $01, $ff
charmap "꽥", HANGUL_POC_ESCAPE, $02, $00
charmap "꽹", HANGUL_POC_ESCAPE, $02, $01
charmap "꾀", HANGUL_POC_ESCAPE, $02, $02
charmap "꾄", HANGUL_POC_ESCAPE, $02, $03
charmap "꾈", HANGUL_POC_ESCAPE, $02, $04
charmap "꾐", HANGUL_POC_ESCAPE, $02, $05
charmap "꾑", HANGUL_POC_ESCAPE, $02, $06
charmap "꾕", HANGUL_POC_ESCAPE, $02, $07
charmap "꾜", HANGUL_POC_ESCAPE, $02, $08
charmap "꾸", HANGUL_POC_ESCAPE, $02, $09
charmap "꾹", HANGUL_POC_ESCAPE, $02, $0a
charmap "꾼", HANGUL_POC_ESCAPE, $02, $0b
charmap "꿀", HANGUL_POC_ESCAPE, $02, $0c
charmap "꿇", HANGUL_POC_ESCAPE, $02, $0d
charmap "꿈", HANGUL_POC_ESCAPE, $02, $0e
charmap "꿉", HANGUL_POC_ESCAPE, $02, $0f
charmap "꿋", HANGUL_POC_ESCAPE, $02, $10
charmap "꿍", HANGUL_POC_ESCAPE, $02, $11
charmap "꿎", HANGUL_POC_ESCAPE, $02, $12
charmap "꿔", HANGUL_POC_ESCAPE, $02, $13
charmap "꿜", HANGUL_POC_ESCAPE, $02, $14
charmap "꿨", HANGUL_POC_ESCAPE, $02, $15
charmap "꿩", HANGUL_POC_ESCAPE, $02, $16
charmap "꿰", HANGUL_POC_ESCAPE, $02, $17
charmap "꿱", HANGUL_POC_ESCAPE, $02, $18
charmap "꿴", HANGUL_POC_ESCAPE, $02, $19
charmap "꿸", HANGUL_POC_ESCAPE, $02, $1a
charmap "뀀", HANGUL_POC_ESCAPE, $02, $1b
charmap "뀁", HANGUL_POC_ESCAPE, $02, $1c
charmap "뀄", HANGUL_POC_ESCAPE, $02, $1d
charmap "뀌", HANGUL_POC_ESCAPE, $02, $1e
charmap "뀐", HANGUL_POC_ESCAPE, $02, $1f
charmap "뀔", HANGUL_POC_ESCAPE, $02, $20
charmap "뀜", HANGUL_POC_ESCAPE, $02, $21
charmap "뀝", HANGUL_POC_ESCAPE, $02, $22
charmap "뀨", HANGUL_POC_ESCAPE, $02, $23
charmap "끄", HANGUL_POC_ESCAPE, $02, $24
charmap "끅", HANGUL_POC_ESCAPE, $02, $25
charmap "끈", HANGUL_POC_ESCAPE, $02, $26
charmap "끊", HANGUL_POC_ESCAPE, $02, $27
charmap "끌", HANGUL_POC_ESCAPE, $02, $28
charmap "끎", HANGUL_POC_ESCAPE, $02, $29
charmap "끓", HANGUL_POC_ESCAPE, $02, $2a
charmap "끔", HANGUL_POC_ESCAPE, $02, $2b
charmap "끕", HANGUL_POC_ESCAPE, $02, $2c
charmap "끗", HANGUL_POC_ESCAPE, $02, $2d
charmap "끙", HANGUL_POC_ESCAPE, $02, $2e
charmap "끝", HANGUL_POC_ESCAPE, $02, $31
charmap "끼", HANGUL_POC_ESCAPE, $02, $32
charmap "끽", HANGUL_POC_ESCAPE, $02, $33
charmap "낀", HANGUL_POC_ESCAPE, $02, $34
charmap "낄", HANGUL_POC_ESCAPE, $02, $35
charmap "낌", HANGUL_POC_ESCAPE, $02, $36
charmap "낍", HANGUL_POC_ESCAPE, $02, $37
charmap "낏", HANGUL_POC_ESCAPE, $02, $38
charmap "낑", HANGUL_POC_ESCAPE, $02, $39
charmap "나", HANGUL_POC_ESCAPE, $02, $3a
charmap "낙", HANGUL_POC_ESCAPE, $02, $3b
charmap "낚", HANGUL_POC_ESCAPE, $02, $3c
charmap "난", HANGUL_POC_ESCAPE, $02, $3d
charmap "낟", HANGUL_POC_ESCAPE, $02, $3e
charmap "날", HANGUL_POC_ESCAPE, $02, $3f
charmap "낡", HANGUL_POC_ESCAPE, $02, $40
charmap "낢", HANGUL_POC_ESCAPE, $02, $41
charmap "남", HANGUL_POC_ESCAPE, $02, $42
charmap "납", HANGUL_POC_ESCAPE, $02, $43
charmap "낫", HANGUL_POC_ESCAPE, $02, $44
charmap "났", HANGUL_POC_ESCAPE, $02, $45
charmap "낭", HANGUL_POC_ESCAPE, $02, $46
charmap "낮", HANGUL_POC_ESCAPE, $02, $47
charmap "낯", HANGUL_POC_ESCAPE, $02, $48
charmap "낱", HANGUL_POC_ESCAPE, $02, $49
charmap "낳", HANGUL_POC_ESCAPE, $02, $4a
charmap "내", HANGUL_POC_ESCAPE, $02, $4b
charmap "낵", HANGUL_POC_ESCAPE, $02, $4c
charmap "낸", HANGUL_POC_ESCAPE, $02, $4d
charmap "낼", HANGUL_POC_ESCAPE, $02, $4e
charmap "냄", HANGUL_POC_ESCAPE, $02, $4f
charmap "냅", HANGUL_POC_ESCAPE, $02, $60
charmap "냇", HANGUL_POC_ESCAPE, $02, $61
charmap "냈", HANGUL_POC_ESCAPE, $02, $62
charmap "냉", HANGUL_POC_ESCAPE, $02, $63
charmap "냐", HANGUL_POC_ESCAPE, $02, $64
charmap "냑", HANGUL_POC_ESCAPE, $02, $65
charmap "냔", HANGUL_POC_ESCAPE, $02, $66
charmap "냘", HANGUL_POC_ESCAPE, $02, $67
charmap "냠", HANGUL_POC_ESCAPE, $02, $68
charmap "냥", HANGUL_POC_ESCAPE, $02, $69
charmap "너", HANGUL_POC_ESCAPE, $02, $6a
charmap "넉", HANGUL_POC_ESCAPE, $02, $6b
charmap "넋", HANGUL_POC_ESCAPE, $02, $6c
charmap "넌", HANGUL_POC_ESCAPE, $02, $6d
charmap "널", HANGUL_POC_ESCAPE, $02, $6e
charmap "넒", HANGUL_POC_ESCAPE, $02, $6f
charmap "넓", HANGUL_POC_ESCAPE, $02, $70
charmap "넘", HANGUL_POC_ESCAPE, $02, $71
charmap "넙", HANGUL_POC_ESCAPE, $02, $72
charmap "넛", HANGUL_POC_ESCAPE, $02, $73
charmap "넜", HANGUL_POC_ESCAPE, $02, $74
charmap "넝", HANGUL_POC_ESCAPE, $02, $75
charmap "넣", HANGUL_POC_ESCAPE, $02, $76
charmap "네", HANGUL_POC_ESCAPE, $02, $77
charmap "넥", HANGUL_POC_ESCAPE, $02, $78
charmap "넨", HANGUL_POC_ESCAPE, $02, $79
charmap "넬", HANGUL_POC_ESCAPE, $02, $7a
charmap "넴", HANGUL_POC_ESCAPE, $02, $7b
charmap "넵", HANGUL_POC_ESCAPE, $02, $7c
charmap "넷", HANGUL_POC_ESCAPE, $02, $7d
charmap "넸", HANGUL_POC_ESCAPE, $02, $7e
charmap "넹", HANGUL_POC_ESCAPE, $02, $7f
charmap "녀", HANGUL_POC_ESCAPE, $02, $80
charmap "녁", HANGUL_POC_ESCAPE, $02, $81
charmap "년", HANGUL_POC_ESCAPE, $02, $82
charmap "녈", HANGUL_POC_ESCAPE, $02, $83
charmap "념", HANGUL_POC_ESCAPE, $02, $84
charmap "녑", HANGUL_POC_ESCAPE, $02, $85
charmap "녔", HANGUL_POC_ESCAPE, $02, $86
charmap "녕", HANGUL_POC_ESCAPE, $02, $87
charmap "녘", HANGUL_POC_ESCAPE, $02, $88
charmap "녜", HANGUL_POC_ESCAPE, $02, $89
charmap "녠", HANGUL_POC_ESCAPE, $02, $8a
charmap "노", HANGUL_POC_ESCAPE, $02, $8b
charmap "녹", HANGUL_POC_ESCAPE, $02, $8c
charmap "논", HANGUL_POC_ESCAPE, $02, $8d
charmap "놀", HANGUL_POC_ESCAPE, $02, $8e
charmap "놂", HANGUL_POC_ESCAPE, $02, $8f
charmap "놈", HANGUL_POC_ESCAPE, $02, $90
charmap "놉", HANGUL_POC_ESCAPE, $02, $91
charmap "놋", HANGUL_POC_ESCAPE, $02, $92
charmap "농", HANGUL_POC_ESCAPE, $02, $93
charmap "높", HANGUL_POC_ESCAPE, $02, $94
charmap "놓", HANGUL_POC_ESCAPE, $02, $95
charmap "놔", HANGUL_POC_ESCAPE, $02, $96
charmap "놘", HANGUL_POC_ESCAPE, $02, $97
charmap "놜", HANGUL_POC_ESCAPE, $02, $98
charmap "놨", HANGUL_POC_ESCAPE, $02, $99
charmap "뇌", HANGUL_POC_ESCAPE, $02, $9a
charmap "뇐", HANGUL_POC_ESCAPE, $02, $9b
charmap "뇔", HANGUL_POC_ESCAPE, $02, $9c
charmap "뇜", HANGUL_POC_ESCAPE, $02, $9d
charmap "뇝", HANGUL_POC_ESCAPE, $02, $9e
charmap "뇟", HANGUL_POC_ESCAPE, $02, $a1
charmap "뇨", HANGUL_POC_ESCAPE, $02, $a2
charmap "뇩", HANGUL_POC_ESCAPE, $02, $a3
charmap "뇬", HANGUL_POC_ESCAPE, $02, $a4
charmap "뇰", HANGUL_POC_ESCAPE, $02, $a5
charmap "뇹", HANGUL_POC_ESCAPE, $02, $a6
charmap "뇻", HANGUL_POC_ESCAPE, $02, $a7
charmap "뇽", HANGUL_POC_ESCAPE, $02, $a8
charmap "누", HANGUL_POC_ESCAPE, $02, $a9
charmap "눅", HANGUL_POC_ESCAPE, $02, $aa
charmap "눈", HANGUL_POC_ESCAPE, $02, $ab
charmap "눋", HANGUL_POC_ESCAPE, $02, $ac
charmap "눌", HANGUL_POC_ESCAPE, $02, $ad
charmap "눔", HANGUL_POC_ESCAPE, $02, $ae
charmap "눕", HANGUL_POC_ESCAPE, $02, $af
charmap "눗", HANGUL_POC_ESCAPE, $02, $b0
charmap "눙", HANGUL_POC_ESCAPE, $02, $b1
charmap "눠", HANGUL_POC_ESCAPE, $02, $b2
charmap "눴", HANGUL_POC_ESCAPE, $02, $b3
charmap "눼", HANGUL_POC_ESCAPE, $02, $b4
charmap "뉘", HANGUL_POC_ESCAPE, $02, $b5
charmap "뉜", HANGUL_POC_ESCAPE, $02, $b6
charmap "뉠", HANGUL_POC_ESCAPE, $02, $b7
charmap "뉨", HANGUL_POC_ESCAPE, $02, $b8
charmap "뉩", HANGUL_POC_ESCAPE, $02, $b9
charmap "뉴", HANGUL_POC_ESCAPE, $02, $ba
charmap "뉵", HANGUL_POC_ESCAPE, $02, $bb
charmap "뉼", HANGUL_POC_ESCAPE, $02, $bc
charmap "늄", HANGUL_POC_ESCAPE, $02, $bd
charmap "늅", HANGUL_POC_ESCAPE, $02, $be
charmap "늉", HANGUL_POC_ESCAPE, $02, $bf
charmap "느", HANGUL_POC_ESCAPE, $02, $c0
charmap "늑", HANGUL_POC_ESCAPE, $02, $c1
charmap "는", HANGUL_POC_ESCAPE, $02, $c2
charmap "늘", HANGUL_POC_ESCAPE, $02, $c3
charmap "늙", HANGUL_POC_ESCAPE, $02, $c4
charmap "늚", HANGUL_POC_ESCAPE, $02, $c5
charmap "늠", HANGUL_POC_ESCAPE, $02, $c6
charmap "늡", HANGUL_POC_ESCAPE, $02, $c7
charmap "늣", HANGUL_POC_ESCAPE, $02, $c8
charmap "능", HANGUL_POC_ESCAPE, $02, $c9
charmap "늦", HANGUL_POC_ESCAPE, $02, $ca
charmap "늪", HANGUL_POC_ESCAPE, $02, $cb
charmap "늬", HANGUL_POC_ESCAPE, $02, $cc
charmap "늰", HANGUL_POC_ESCAPE, $02, $cd
charmap "늴", HANGUL_POC_ESCAPE, $02, $ce
charmap "니", HANGUL_POC_ESCAPE, $02, $cf
charmap "닉", HANGUL_POC_ESCAPE, $02, $d0
charmap "닌", HANGUL_POC_ESCAPE, $02, $d1
charmap "닐", HANGUL_POC_ESCAPE, $02, $d2
charmap "닒", HANGUL_POC_ESCAPE, $02, $d3
charmap "님", HANGUL_POC_ESCAPE, $02, $d4
charmap "닙", HANGUL_POC_ESCAPE, $02, $d5
charmap "닛", HANGUL_POC_ESCAPE, $02, $d6
charmap "닝", HANGUL_POC_ESCAPE, $02, $d7
charmap "닢", HANGUL_POC_ESCAPE, $02, $d8
charmap "다", HANGUL_POC_ESCAPE, $02, $d9
charmap "닥", HANGUL_POC_ESCAPE, $02, $da
charmap "닦", HANGUL_POC_ESCAPE, $02, $db
charmap "단", HANGUL_POC_ESCAPE, $02, $dc
charmap "닫", HANGUL_POC_ESCAPE, $02, $dd
charmap "달", HANGUL_POC_ESCAPE, $02, $de
charmap "닭", HANGUL_POC_ESCAPE, $02, $df
charmap "닮", HANGUL_POC_ESCAPE, $02, $e0
charmap "닯", HANGUL_POC_ESCAPE, $02, $e1
charmap "닳", HANGUL_POC_ESCAPE, $02, $e2
charmap "담", HANGUL_POC_ESCAPE, $02, $e3
charmap "답", HANGUL_POC_ESCAPE, $02, $e4
charmap "닷", HANGUL_POC_ESCAPE, $02, $e5
charmap "닸", HANGUL_POC_ESCAPE, $02, $e6
charmap "당", HANGUL_POC_ESCAPE, $02, $e7
charmap "닺", HANGUL_POC_ESCAPE, $02, $e8
charmap "닻", HANGUL_POC_ESCAPE, $02, $e9
charmap "닿", HANGUL_POC_ESCAPE, $02, $ea
charmap "대", HANGUL_POC_ESCAPE, $02, $eb
charmap "댁", HANGUL_POC_ESCAPE, $02, $ec
charmap "댄", HANGUL_POC_ESCAPE, $02, $ed
charmap "댈", HANGUL_POC_ESCAPE, $02, $ee
charmap "댐", HANGUL_POC_ESCAPE, $02, $ef
charmap "댑", HANGUL_POC_ESCAPE, $02, $f0
charmap "댓", HANGUL_POC_ESCAPE, $02, $f1
charmap "댔", HANGUL_POC_ESCAPE, $02, $f2
charmap "댕", HANGUL_POC_ESCAPE, $02, $f3
charmap "더", HANGUL_POC_ESCAPE, $02, $f5
charmap "덕", HANGUL_POC_ESCAPE, $02, $f6
charmap "덖", HANGUL_POC_ESCAPE, $02, $f7
charmap "던", HANGUL_POC_ESCAPE, $02, $f8
charmap "덛", HANGUL_POC_ESCAPE, $02, $f9
charmap "덜", HANGUL_POC_ESCAPE, $02, $fa
charmap "덞", HANGUL_POC_ESCAPE, $02, $fb
charmap "덟", HANGUL_POC_ESCAPE, $02, $fc
charmap "덤", HANGUL_POC_ESCAPE, $02, $fd
charmap "덥", HANGUL_POC_ESCAPE, $02, $fe
charmap "덧", HANGUL_POC_ESCAPE, $03, $01
charmap "덩", HANGUL_POC_ESCAPE, $03, $02
charmap "덫", HANGUL_POC_ESCAPE, $03, $03
charmap "덮", HANGUL_POC_ESCAPE, $03, $04
charmap "데", HANGUL_POC_ESCAPE, $03, $05
charmap "덱", HANGUL_POC_ESCAPE, $03, $06
charmap "덴", HANGUL_POC_ESCAPE, $03, $07
charmap "델", HANGUL_POC_ESCAPE, $03, $08
charmap "뎀", HANGUL_POC_ESCAPE, $03, $09
charmap "뎁", HANGUL_POC_ESCAPE, $03, $0a
charmap "뎃", HANGUL_POC_ESCAPE, $03, $0b
charmap "뎄", HANGUL_POC_ESCAPE, $03, $0c
charmap "뎅", HANGUL_POC_ESCAPE, $03, $0d
charmap "뎌", HANGUL_POC_ESCAPE, $03, $0e
charmap "뎐", HANGUL_POC_ESCAPE, $03, $0f
charmap "뎔", HANGUL_POC_ESCAPE, $03, $10
charmap "뎠", HANGUL_POC_ESCAPE, $03, $11
charmap "뎡", HANGUL_POC_ESCAPE, $03, $12
charmap "뎨", HANGUL_POC_ESCAPE, $03, $13
charmap "뎬", HANGUL_POC_ESCAPE, $03, $14
charmap "도", HANGUL_POC_ESCAPE, $03, $15
charmap "독", HANGUL_POC_ESCAPE, $03, $16
charmap "돈", HANGUL_POC_ESCAPE, $03, $17
charmap "돋", HANGUL_POC_ESCAPE, $03, $18
charmap "돌", HANGUL_POC_ESCAPE, $03, $19
charmap "돎", HANGUL_POC_ESCAPE, $03, $1a
charmap "돔", HANGUL_POC_ESCAPE, $03, $1c
charmap "돕", HANGUL_POC_ESCAPE, $03, $1d
charmap "돗", HANGUL_POC_ESCAPE, $03, $1e
charmap "동", HANGUL_POC_ESCAPE, $03, $1f
charmap "돛", HANGUL_POC_ESCAPE, $03, $20
charmap "돝", HANGUL_POC_ESCAPE, $03, $21
charmap "돠", HANGUL_POC_ESCAPE, $03, $22
charmap "돤", HANGUL_POC_ESCAPE, $03, $23
charmap "돨", HANGUL_POC_ESCAPE, $03, $24
charmap "돼", HANGUL_POC_ESCAPE, $03, $25
charmap "됐", HANGUL_POC_ESCAPE, $03, $26
charmap "되", HANGUL_POC_ESCAPE, $03, $27
charmap "된", HANGUL_POC_ESCAPE, $03, $28
charmap "될", HANGUL_POC_ESCAPE, $03, $29
charmap "됨", HANGUL_POC_ESCAPE, $03, $2a
charmap "됩", HANGUL_POC_ESCAPE, $03, $2b
charmap "됫", HANGUL_POC_ESCAPE, $03, $2c
charmap "됴", HANGUL_POC_ESCAPE, $03, $2d
charmap "두", HANGUL_POC_ESCAPE, $03, $2e
charmap "둑", HANGUL_POC_ESCAPE, $03, $2f
charmap "둔", HANGUL_POC_ESCAPE, $03, $30
charmap "둘", HANGUL_POC_ESCAPE, $03, $31
charmap "둠", HANGUL_POC_ESCAPE, $03, $32
charmap "둡", HANGUL_POC_ESCAPE, $03, $33
charmap "둣", HANGUL_POC_ESCAPE, $03, $34
charmap "둥", HANGUL_POC_ESCAPE, $03, $35
charmap "둬", HANGUL_POC_ESCAPE, $03, $36
charmap "뒀", HANGUL_POC_ESCAPE, $03, $37
charmap "뒈", HANGUL_POC_ESCAPE, $03, $38
charmap "뒝", HANGUL_POC_ESCAPE, $03, $39
charmap "뒤", HANGUL_POC_ESCAPE, $03, $3a
charmap "뒨", HANGUL_POC_ESCAPE, $03, $3b
charmap "뒬", HANGUL_POC_ESCAPE, $03, $3c
charmap "뒵", HANGUL_POC_ESCAPE, $03, $3d
charmap "뒷", HANGUL_POC_ESCAPE, $03, $3e
charmap "뒹", HANGUL_POC_ESCAPE, $03, $3f
charmap "듀", HANGUL_POC_ESCAPE, $03, $40
charmap "듄", HANGUL_POC_ESCAPE, $03, $41
charmap "듈", HANGUL_POC_ESCAPE, $03, $42
charmap "듐", HANGUL_POC_ESCAPE, $03, $43
charmap "듕", HANGUL_POC_ESCAPE, $03, $44
charmap "드", HANGUL_POC_ESCAPE, $03, $45
charmap "득", HANGUL_POC_ESCAPE, $03, $46
charmap "든", HANGUL_POC_ESCAPE, $03, $47
charmap "듣", HANGUL_POC_ESCAPE, $03, $48
charmap "들", HANGUL_POC_ESCAPE, $03, $49
charmap "듦", HANGUL_POC_ESCAPE, $03, $4a
charmap "듬", HANGUL_POC_ESCAPE, $03, $4b
charmap "듭", HANGUL_POC_ESCAPE, $03, $4c
charmap "듯", HANGUL_POC_ESCAPE, $03, $4d
charmap "등", HANGUL_POC_ESCAPE, $03, $4e
charmap "듸", HANGUL_POC_ESCAPE, $03, $4f
charmap "디", HANGUL_POC_ESCAPE, $03, $60
charmap "딕", HANGUL_POC_ESCAPE, $03, $61
charmap "딘", HANGUL_POC_ESCAPE, $03, $62
charmap "딛", HANGUL_POC_ESCAPE, $03, $63
charmap "딜", HANGUL_POC_ESCAPE, $03, $64
charmap "딤", HANGUL_POC_ESCAPE, $03, $65
charmap "딥", HANGUL_POC_ESCAPE, $03, $66
charmap "딧", HANGUL_POC_ESCAPE, $03, $67
charmap "딨", HANGUL_POC_ESCAPE, $03, $68
charmap "딩", HANGUL_POC_ESCAPE, $03, $69
charmap "딪", HANGUL_POC_ESCAPE, $03, $6a
charmap "따", HANGUL_POC_ESCAPE, $03, $6b
charmap "딱", HANGUL_POC_ESCAPE, $03, $6c
charmap "딴", HANGUL_POC_ESCAPE, $03, $6d
charmap "딸", HANGUL_POC_ESCAPE, $03, $6e
charmap "땀", HANGUL_POC_ESCAPE, $03, $71
charmap "땁", HANGUL_POC_ESCAPE, $03, $72
charmap "땃", HANGUL_POC_ESCAPE, $03, $73
charmap "땄", HANGUL_POC_ESCAPE, $03, $74
charmap "땅", HANGUL_POC_ESCAPE, $03, $75
charmap "땋", HANGUL_POC_ESCAPE, $03, $76
charmap "때", HANGUL_POC_ESCAPE, $03, $77
charmap "땍", HANGUL_POC_ESCAPE, $03, $78
charmap "땐", HANGUL_POC_ESCAPE, $03, $79
charmap "땔", HANGUL_POC_ESCAPE, $03, $7a
charmap "땜", HANGUL_POC_ESCAPE, $03, $7b
charmap "땝", HANGUL_POC_ESCAPE, $03, $7c
charmap "땟", HANGUL_POC_ESCAPE, $03, $7d
charmap "땠", HANGUL_POC_ESCAPE, $03, $7e
charmap "땡", HANGUL_POC_ESCAPE, $03, $7f
charmap "떠", HANGUL_POC_ESCAPE, $03, $80
charmap "떡", HANGUL_POC_ESCAPE, $03, $81
charmap "떤", HANGUL_POC_ESCAPE, $03, $82
charmap "떨", HANGUL_POC_ESCAPE, $03, $83
charmap "떪", HANGUL_POC_ESCAPE, $03, $84
charmap "떫", HANGUL_POC_ESCAPE, $03, $85
charmap "떰", HANGUL_POC_ESCAPE, $03, $86
charmap "떱", HANGUL_POC_ESCAPE, $03, $87
charmap "떳", HANGUL_POC_ESCAPE, $03, $88
charmap "떴", HANGUL_POC_ESCAPE, $03, $89
charmap "떵", HANGUL_POC_ESCAPE, $03, $8a
charmap "떻", HANGUL_POC_ESCAPE, $03, $8b
charmap "떼", HANGUL_POC_ESCAPE, $03, $8c
charmap "떽", HANGUL_POC_ESCAPE, $03, $8d
charmap "뗀", HANGUL_POC_ESCAPE, $03, $8e
charmap "뗄", HANGUL_POC_ESCAPE, $03, $8f
charmap "뗌", HANGUL_POC_ESCAPE, $03, $90
charmap "뗍", HANGUL_POC_ESCAPE, $03, $91
charmap "뗏", HANGUL_POC_ESCAPE, $03, $92
charmap "뗐", HANGUL_POC_ESCAPE, $03, $93
charmap "뗑", HANGUL_POC_ESCAPE, $03, $94
charmap "뗘", HANGUL_POC_ESCAPE, $03, $95
charmap "뗬", HANGUL_POC_ESCAPE, $03, $96
charmap "또", HANGUL_POC_ESCAPE, $03, $97
charmap "똑", HANGUL_POC_ESCAPE, $03, $98
charmap "똔", HANGUL_POC_ESCAPE, $03, $99
charmap "똘", HANGUL_POC_ESCAPE, $03, $9a
charmap "똥", HANGUL_POC_ESCAPE, $03, $9b
charmap "똬", HANGUL_POC_ESCAPE, $03, $9c
charmap "똴", HANGUL_POC_ESCAPE, $03, $9d
charmap "뙈", HANGUL_POC_ESCAPE, $03, $9e
charmap "뙤", HANGUL_POC_ESCAPE, $03, $9f
charmap "뙨", HANGUL_POC_ESCAPE, $03, $a0
charmap "뚜", HANGUL_POC_ESCAPE, $03, $a1
charmap "뚝", HANGUL_POC_ESCAPE, $03, $a2
charmap "뚠", HANGUL_POC_ESCAPE, $03, $a3
charmap "뚤", HANGUL_POC_ESCAPE, $03, $a4
charmap "뚫", HANGUL_POC_ESCAPE, $03, $a5
charmap "뚬", HANGUL_POC_ESCAPE, $03, $a6
charmap "뚱", HANGUL_POC_ESCAPE, $03, $a7
charmap "뛔", HANGUL_POC_ESCAPE, $03, $a8
charmap "뛰", HANGUL_POC_ESCAPE, $03, $a9
charmap "뛴", HANGUL_POC_ESCAPE, $03, $aa
charmap "뛸", HANGUL_POC_ESCAPE, $03, $ab
charmap "뜀", HANGUL_POC_ESCAPE, $03, $ac
charmap "뜁", HANGUL_POC_ESCAPE, $03, $ad
charmap "뜅", HANGUL_POC_ESCAPE, $03, $ae
charmap "뜨", HANGUL_POC_ESCAPE, $03, $af
charmap "뜩", HANGUL_POC_ESCAPE, $03, $b0
charmap "뜬", HANGUL_POC_ESCAPE, $03, $b1
charmap "뜯", HANGUL_POC_ESCAPE, $03, $b2
charmap "뜰", HANGUL_POC_ESCAPE, $03, $b3
charmap "뜸", HANGUL_POC_ESCAPE, $03, $b4
charmap "뜹", HANGUL_POC_ESCAPE, $03, $b5
charmap "뜻", HANGUL_POC_ESCAPE, $03, $b6
charmap "띄", HANGUL_POC_ESCAPE, $03, $b7
charmap "띈", HANGUL_POC_ESCAPE, $03, $b8
charmap "띌", HANGUL_POC_ESCAPE, $03, $b9
charmap "띔", HANGUL_POC_ESCAPE, $03, $ba
charmap "띕", HANGUL_POC_ESCAPE, $03, $bb
charmap "띠", HANGUL_POC_ESCAPE, $03, $bc
charmap "띤", HANGUL_POC_ESCAPE, $03, $bd
charmap "띨", HANGUL_POC_ESCAPE, $03, $be
charmap "띰", HANGUL_POC_ESCAPE, $03, $bf
charmap "띱", HANGUL_POC_ESCAPE, $03, $c0
charmap "띳", HANGUL_POC_ESCAPE, $03, $c1
charmap "띵", HANGUL_POC_ESCAPE, $03, $c2
charmap "라", HANGUL_POC_ESCAPE, $03, $c3
charmap "락", HANGUL_POC_ESCAPE, $03, $c4
charmap "란", HANGUL_POC_ESCAPE, $03, $c5
charmap "랄", HANGUL_POC_ESCAPE, $03, $c6
charmap "람", HANGUL_POC_ESCAPE, $03, $c7
charmap "랍", HANGUL_POC_ESCAPE, $03, $c8
charmap "랏", HANGUL_POC_ESCAPE, $03, $c9
charmap "랐", HANGUL_POC_ESCAPE, $03, $ca
charmap "랑", HANGUL_POC_ESCAPE, $03, $cb
charmap "랒", HANGUL_POC_ESCAPE, $03, $cc
charmap "랖", HANGUL_POC_ESCAPE, $03, $cd
charmap "랗", HANGUL_POC_ESCAPE, $03, $ce
charmap "뢔", HANGUL_POC_ESCAPE, $03, $d0
charmap "래", HANGUL_POC_ESCAPE, $03, $d1
charmap "랙", HANGUL_POC_ESCAPE, $03, $d2
charmap "랜", HANGUL_POC_ESCAPE, $03, $d3
charmap "랠", HANGUL_POC_ESCAPE, $03, $d4
charmap "램", HANGUL_POC_ESCAPE, $03, $d5
charmap "랩", HANGUL_POC_ESCAPE, $03, $d6
charmap "랫", HANGUL_POC_ESCAPE, $03, $d7
charmap "랬", HANGUL_POC_ESCAPE, $03, $d8
charmap "랭", HANGUL_POC_ESCAPE, $03, $d9
charmap "랴", HANGUL_POC_ESCAPE, $03, $da
charmap "략", HANGUL_POC_ESCAPE, $03, $db
charmap "랸", HANGUL_POC_ESCAPE, $03, $dc
charmap "럇", HANGUL_POC_ESCAPE, $03, $dd
charmap "량", HANGUL_POC_ESCAPE, $03, $de
charmap "러", HANGUL_POC_ESCAPE, $03, $df
charmap "럭", HANGUL_POC_ESCAPE, $03, $e0
charmap "런", HANGUL_POC_ESCAPE, $03, $e1
charmap "럴", HANGUL_POC_ESCAPE, $03, $e2
charmap "럼", HANGUL_POC_ESCAPE, $03, $e3
charmap "럽", HANGUL_POC_ESCAPE, $03, $e4
charmap "럿", HANGUL_POC_ESCAPE, $03, $e5
charmap "렀", HANGUL_POC_ESCAPE, $03, $e6
charmap "렁", HANGUL_POC_ESCAPE, $03, $e7
charmap "렇", HANGUL_POC_ESCAPE, $03, $e8
charmap "레", HANGUL_POC_ESCAPE, $03, $e9
charmap "렉", HANGUL_POC_ESCAPE, $03, $ea
charmap "렌", HANGUL_POC_ESCAPE, $03, $eb
charmap "렐", HANGUL_POC_ESCAPE, $03, $ec
charmap "렘", HANGUL_POC_ESCAPE, $03, $ed
charmap "렙", HANGUL_POC_ESCAPE, $03, $ee
charmap "렛", HANGUL_POC_ESCAPE, $03, $ef
charmap "렝", HANGUL_POC_ESCAPE, $03, $f0
charmap "려", HANGUL_POC_ESCAPE, $03, $f1
charmap "련", HANGUL_POC_ESCAPE, $03, $f3
charmap "렬", HANGUL_POC_ESCAPE, $03, $f4
charmap "렴", HANGUL_POC_ESCAPE, $03, $f5
charmap "렵", HANGUL_POC_ESCAPE, $03, $f6
charmap "렷", HANGUL_POC_ESCAPE, $03, $f7
charmap "렸", HANGUL_POC_ESCAPE, $03, $f8
charmap "령", HANGUL_POC_ESCAPE, $03, $f9
charmap "례", HANGUL_POC_ESCAPE, $03, $fa
charmap "롄", HANGUL_POC_ESCAPE, $03, $fb
charmap "롑", HANGUL_POC_ESCAPE, $03, $fc
charmap "롓", HANGUL_POC_ESCAPE, $03, $fd
charmap "로", HANGUL_POC_ESCAPE, $03, $fe
charmap "록", HANGUL_POC_ESCAPE, $03, $ff
charmap "론", HANGUL_POC_ESCAPE, $04, $00
charmap "롤", HANGUL_POC_ESCAPE, $04, $01
charmap "롬", HANGUL_POC_ESCAPE, $04, $02
charmap "롭", HANGUL_POC_ESCAPE, $04, $03
charmap "롯", HANGUL_POC_ESCAPE, $04, $04
charmap "롱", HANGUL_POC_ESCAPE, $04, $05
charmap "롸", HANGUL_POC_ESCAPE, $04, $06
charmap "롼", HANGUL_POC_ESCAPE, $04, $07
charmap "뢍", HANGUL_POC_ESCAPE, $04, $08
charmap "뢨", HANGUL_POC_ESCAPE, $04, $09
charmap "뢰", HANGUL_POC_ESCAPE, $04, $0a
charmap "뢴", HANGUL_POC_ESCAPE, $04, $0b
charmap "뢸", HANGUL_POC_ESCAPE, $04, $0c
charmap "룀", HANGUL_POC_ESCAPE, $04, $0d
charmap "룁", HANGUL_POC_ESCAPE, $04, $0e
charmap "룃", HANGUL_POC_ESCAPE, $04, $0f
charmap "룅", HANGUL_POC_ESCAPE, $04, $10
charmap "료", HANGUL_POC_ESCAPE, $04, $11
charmap "룐", HANGUL_POC_ESCAPE, $04, $12
charmap "룔", HANGUL_POC_ESCAPE, $04, $13
charmap "룝", HANGUL_POC_ESCAPE, $04, $14
charmap "룟", HANGUL_POC_ESCAPE, $04, $15
charmap "룡", HANGUL_POC_ESCAPE, $04, $16
charmap "루", HANGUL_POC_ESCAPE, $04, $17
charmap "룩", HANGUL_POC_ESCAPE, $04, $18
charmap "룬", HANGUL_POC_ESCAPE, $04, $19
charmap "룰", HANGUL_POC_ESCAPE, $04, $1a
charmap "룸", HANGUL_POC_ESCAPE, $04, $1b
charmap "룹", HANGUL_POC_ESCAPE, $04, $1c
charmap "룻", HANGUL_POC_ESCAPE, $04, $1d
charmap "룽", HANGUL_POC_ESCAPE, $04, $1e
charmap "뤄", HANGUL_POC_ESCAPE, $04, $1f
charmap "뤘", HANGUL_POC_ESCAPE, $04, $20
charmap "뤠", HANGUL_POC_ESCAPE, $04, $21
charmap "뤼", HANGUL_POC_ESCAPE, $04, $22
charmap "뤽", HANGUL_POC_ESCAPE, $04, $23
charmap "륀", HANGUL_POC_ESCAPE, $04, $24
charmap "륄", HANGUL_POC_ESCAPE, $04, $25
charmap "륌", HANGUL_POC_ESCAPE, $04, $26
charmap "륏", HANGUL_POC_ESCAPE, $04, $27
charmap "륑", HANGUL_POC_ESCAPE, $04, $28
charmap "류", HANGUL_POC_ESCAPE, $04, $29
charmap "륙", HANGUL_POC_ESCAPE, $04, $2a
charmap "륜", HANGUL_POC_ESCAPE, $04, $2b
charmap "률", HANGUL_POC_ESCAPE, $04, $2c
charmap "륨", HANGUL_POC_ESCAPE, $04, $2d
charmap "륩", HANGUL_POC_ESCAPE, $04, $2e
charmap "륫", HANGUL_POC_ESCAPE, $04, $31
charmap "륭", HANGUL_POC_ESCAPE, $04, $32
charmap "르", HANGUL_POC_ESCAPE, $04, $33
charmap "륵", HANGUL_POC_ESCAPE, $04, $34
charmap "른", HANGUL_POC_ESCAPE, $04, $35
charmap "를", HANGUL_POC_ESCAPE, $04, $36
charmap "름", HANGUL_POC_ESCAPE, $04, $37
charmap "릅", HANGUL_POC_ESCAPE, $04, $38
charmap "릇", HANGUL_POC_ESCAPE, $04, $39
charmap "릉", HANGUL_POC_ESCAPE, $04, $3a
charmap "릊", HANGUL_POC_ESCAPE, $04, $3b
charmap "릍", HANGUL_POC_ESCAPE, $04, $3c
charmap "릎", HANGUL_POC_ESCAPE, $04, $3d
charmap "리", HANGUL_POC_ESCAPE, $04, $3e
charmap "릭", HANGUL_POC_ESCAPE, $04, $3f
charmap "린", HANGUL_POC_ESCAPE, $04, $40
charmap "릴", HANGUL_POC_ESCAPE, $04, $41
charmap "림", HANGUL_POC_ESCAPE, $04, $42
charmap "립", HANGUL_POC_ESCAPE, $04, $43
charmap "릿", HANGUL_POC_ESCAPE, $04, $44
charmap "링", HANGUL_POC_ESCAPE, $04, $45
charmap "마", HANGUL_POC_ESCAPE, $04, $46
charmap "막", HANGUL_POC_ESCAPE, $04, $47
charmap "만", HANGUL_POC_ESCAPE, $04, $48
charmap "많", HANGUL_POC_ESCAPE, $04, $49
charmap "맏", HANGUL_POC_ESCAPE, $04, $4a
charmap "말", HANGUL_POC_ESCAPE, $04, $4b
charmap "맑", HANGUL_POC_ESCAPE, $04, $4c
charmap "맒", HANGUL_POC_ESCAPE, $04, $4d
charmap "맘", HANGUL_POC_ESCAPE, $04, $4e
charmap "맙", HANGUL_POC_ESCAPE, $04, $4f
charmap "맛", HANGUL_POC_ESCAPE, $04, $60
charmap "망", HANGUL_POC_ESCAPE, $04, $61
charmap "맞", HANGUL_POC_ESCAPE, $04, $62
charmap "맡", HANGUL_POC_ESCAPE, $04, $63
charmap "맣", HANGUL_POC_ESCAPE, $04, $64
charmap "매", HANGUL_POC_ESCAPE, $04, $65
charmap "맥", HANGUL_POC_ESCAPE, $04, $66
charmap "맨", HANGUL_POC_ESCAPE, $04, $67
charmap "맬", HANGUL_POC_ESCAPE, $04, $68
charmap "맴", HANGUL_POC_ESCAPE, $04, $69
charmap "맵", HANGUL_POC_ESCAPE, $04, $6a
charmap "맷", HANGUL_POC_ESCAPE, $04, $6b
charmap "맸", HANGUL_POC_ESCAPE, $04, $6c
charmap "맹", HANGUL_POC_ESCAPE, $04, $6d
charmap "맺", HANGUL_POC_ESCAPE, $04, $6e
charmap "먀", HANGUL_POC_ESCAPE, $04, $6f
charmap "먁", HANGUL_POC_ESCAPE, $04, $70
charmap "먈", HANGUL_POC_ESCAPE, $04, $71
charmap "먕", HANGUL_POC_ESCAPE, $04, $72
charmap "머", HANGUL_POC_ESCAPE, $04, $73
charmap "먹", HANGUL_POC_ESCAPE, $04, $74
charmap "먼", HANGUL_POC_ESCAPE, $04, $75
charmap "멀", HANGUL_POC_ESCAPE, $04, $76
charmap "멂", HANGUL_POC_ESCAPE, $04, $77
charmap "멈", HANGUL_POC_ESCAPE, $04, $78
charmap "멉", HANGUL_POC_ESCAPE, $04, $79
charmap "멋", HANGUL_POC_ESCAPE, $04, $7a
charmap "멍", HANGUL_POC_ESCAPE, $04, $7b
charmap "멎", HANGUL_POC_ESCAPE, $04, $7c
charmap "멓", HANGUL_POC_ESCAPE, $04, $7d
charmap "메", HANGUL_POC_ESCAPE, $04, $7e
charmap "멕", HANGUL_POC_ESCAPE, $04, $7f
charmap "멘", HANGUL_POC_ESCAPE, $04, $80
charmap "멜", HANGUL_POC_ESCAPE, $04, $81
charmap "멤", HANGUL_POC_ESCAPE, $04, $82
charmap "멥", HANGUL_POC_ESCAPE, $04, $83
charmap "멧", HANGUL_POC_ESCAPE, $04, $84
charmap "멨", HANGUL_POC_ESCAPE, $04, $85
charmap "멩", HANGUL_POC_ESCAPE, $04, $86
charmap "며", HANGUL_POC_ESCAPE, $04, $87
charmap "멱", HANGUL_POC_ESCAPE, $04, $88
charmap "면", HANGUL_POC_ESCAPE, $04, $89
charmap "멸", HANGUL_POC_ESCAPE, $04, $8a
charmap "몃", HANGUL_POC_ESCAPE, $04, $8b
charmap "몄", HANGUL_POC_ESCAPE, $04, $8c
charmap "명", HANGUL_POC_ESCAPE, $04, $8d
charmap "몇", HANGUL_POC_ESCAPE, $04, $8e
charmap "몌", HANGUL_POC_ESCAPE, $04, $8f
charmap "모", HANGUL_POC_ESCAPE, $04, $90
charmap "목", HANGUL_POC_ESCAPE, $04, $91
charmap "몫", HANGUL_POC_ESCAPE, $04, $92
charmap "몬", HANGUL_POC_ESCAPE, $04, $93
charmap "몰", HANGUL_POC_ESCAPE, $04, $94
charmap "몲", HANGUL_POC_ESCAPE, $04, $95
charmap "몸", HANGUL_POC_ESCAPE, $04, $96
charmap "몹", HANGUL_POC_ESCAPE, $04, $97
charmap "못", HANGUL_POC_ESCAPE, $04, $98
charmap "몽", HANGUL_POC_ESCAPE, $04, $99
charmap "뫄", HANGUL_POC_ESCAPE, $04, $9a
charmap "뫈", HANGUL_POC_ESCAPE, $04, $9b
charmap "뫘", HANGUL_POC_ESCAPE, $04, $9c
charmap "뫙", HANGUL_POC_ESCAPE, $04, $9d
charmap "뫼", HANGUL_POC_ESCAPE, $04, $9e
charmap "묀", HANGUL_POC_ESCAPE, $04, $a1
charmap "묄", HANGUL_POC_ESCAPE, $04, $a2
charmap "묍", HANGUL_POC_ESCAPE, $04, $a3
charmap "묏", HANGUL_POC_ESCAPE, $04, $a4
charmap "묑", HANGUL_POC_ESCAPE, $04, $a5
charmap "묘", HANGUL_POC_ESCAPE, $04, $a6
charmap "묜", HANGUL_POC_ESCAPE, $04, $a7
charmap "묠", HANGUL_POC_ESCAPE, $04, $a8
charmap "묩", HANGUL_POC_ESCAPE, $04, $a9
charmap "묫", HANGUL_POC_ESCAPE, $04, $aa
charmap "무", HANGUL_POC_ESCAPE, $04, $ab
charmap "묵", HANGUL_POC_ESCAPE, $04, $ac
charmap "묶", HANGUL_POC_ESCAPE, $04, $ad
charmap "문", HANGUL_POC_ESCAPE, $04, $ae
charmap "묻", HANGUL_POC_ESCAPE, $04, $af
charmap "물", HANGUL_POC_ESCAPE, $04, $b0
charmap "묽", HANGUL_POC_ESCAPE, $04, $b1
charmap "묾", HANGUL_POC_ESCAPE, $04, $b2
charmap "뭄", HANGUL_POC_ESCAPE, $04, $b3
charmap "뭅", HANGUL_POC_ESCAPE, $04, $b4
charmap "뭇", HANGUL_POC_ESCAPE, $04, $b5
charmap "뭉", HANGUL_POC_ESCAPE, $04, $b6
charmap "뭍", HANGUL_POC_ESCAPE, $04, $b7
charmap "뭏", HANGUL_POC_ESCAPE, $04, $b8
charmap "뭐", HANGUL_POC_ESCAPE, $04, $b9
charmap "뭔", HANGUL_POC_ESCAPE, $04, $ba
charmap "뭘", HANGUL_POC_ESCAPE, $04, $bb
charmap "뭡", HANGUL_POC_ESCAPE, $04, $bc
charmap "뭣", HANGUL_POC_ESCAPE, $04, $bd
charmap "뭬", HANGUL_POC_ESCAPE, $04, $be
charmap "뮈", HANGUL_POC_ESCAPE, $04, $bf
charmap "뮌", HANGUL_POC_ESCAPE, $04, $c0
charmap "뮐", HANGUL_POC_ESCAPE, $04, $c1
charmap "뮤", HANGUL_POC_ESCAPE, $04, $c2
charmap "뮨", HANGUL_POC_ESCAPE, $04, $c3
charmap "뮬", HANGUL_POC_ESCAPE, $04, $c4
charmap "뮴", HANGUL_POC_ESCAPE, $04, $c5
charmap "뮷", HANGUL_POC_ESCAPE, $04, $c6
charmap "므", HANGUL_POC_ESCAPE, $04, $c7
charmap "믄", HANGUL_POC_ESCAPE, $04, $c8
charmap "믈", HANGUL_POC_ESCAPE, $04, $c9
charmap "믐", HANGUL_POC_ESCAPE, $04, $ca
charmap "믓", HANGUL_POC_ESCAPE, $04, $cb
charmap "미", HANGUL_POC_ESCAPE, $04, $cc
charmap "믹", HANGUL_POC_ESCAPE, $04, $cd
charmap "민", HANGUL_POC_ESCAPE, $04, $ce
charmap "믿", HANGUL_POC_ESCAPE, $04, $cf
charmap "밀", HANGUL_POC_ESCAPE, $04, $d0
charmap "밂", HANGUL_POC_ESCAPE, $04, $d1
charmap "밈", HANGUL_POC_ESCAPE, $04, $d2
charmap "밉", HANGUL_POC_ESCAPE, $04, $d3
charmap "밋", HANGUL_POC_ESCAPE, $04, $d4
charmap "밌", HANGUL_POC_ESCAPE, $04, $d5
charmap "밍", HANGUL_POC_ESCAPE, $04, $d6
charmap "및", HANGUL_POC_ESCAPE, $04, $d7
charmap "밑", HANGUL_POC_ESCAPE, $04, $d8
charmap "바", HANGUL_POC_ESCAPE, $04, $d9
charmap "박", HANGUL_POC_ESCAPE, $04, $da
charmap "밖", HANGUL_POC_ESCAPE, $04, $db
charmap "밗", HANGUL_POC_ESCAPE, $04, $dc
charmap "반", HANGUL_POC_ESCAPE, $04, $dd
charmap "받", HANGUL_POC_ESCAPE, $04, $de
charmap "발", HANGUL_POC_ESCAPE, $04, $df
charmap "밝", HANGUL_POC_ESCAPE, $04, $e0
charmap "밞", HANGUL_POC_ESCAPE, $04, $e1
charmap "밟", HANGUL_POC_ESCAPE, $04, $e2
charmap "밤", HANGUL_POC_ESCAPE, $04, $e3
charmap "밥", HANGUL_POC_ESCAPE, $04, $e4
charmap "밧", HANGUL_POC_ESCAPE, $04, $e5
charmap "방", HANGUL_POC_ESCAPE, $04, $e6
charmap "밭", HANGUL_POC_ESCAPE, $04, $e7
charmap "배", HANGUL_POC_ESCAPE, $04, $e8
charmap "백", HANGUL_POC_ESCAPE, $04, $e9
charmap "밴", HANGUL_POC_ESCAPE, $04, $ea
charmap "밸", HANGUL_POC_ESCAPE, $04, $eb
charmap "뱀", HANGUL_POC_ESCAPE, $04, $ec
charmap "뱁", HANGUL_POC_ESCAPE, $04, $ed
charmap "뱃", HANGUL_POC_ESCAPE, $04, $ee
charmap "뱄", HANGUL_POC_ESCAPE, $04, $ef
charmap "뱅", HANGUL_POC_ESCAPE, $04, $f0
charmap "뱉", HANGUL_POC_ESCAPE, $04, $f1
charmap "뱌", HANGUL_POC_ESCAPE, $04, $f2
charmap "뱍", HANGUL_POC_ESCAPE, $04, $f3
charmap "뱐", HANGUL_POC_ESCAPE, $04, $f4
charmap "뱝", HANGUL_POC_ESCAPE, $04, $f5
charmap "버", HANGUL_POC_ESCAPE, $04, $f6
charmap "벅", HANGUL_POC_ESCAPE, $04, $f7
charmap "번", HANGUL_POC_ESCAPE, $04, $f8
charmap "벋", HANGUL_POC_ESCAPE, $04, $f9
charmap "벌", HANGUL_POC_ESCAPE, $04, $fa
charmap "벎", HANGUL_POC_ESCAPE, $04, $fb
charmap "범", HANGUL_POC_ESCAPE, $04, $fc
charmap "법", HANGUL_POC_ESCAPE, $04, $fd
charmap "벗", HANGUL_POC_ESCAPE, $04, $fe
charmap "벙", HANGUL_POC_ESCAPE, $05, $01
charmap "벚", HANGUL_POC_ESCAPE, $05, $02
charmap "베", HANGUL_POC_ESCAPE, $05, $03
charmap "벡", HANGUL_POC_ESCAPE, $05, $04
charmap "벤", HANGUL_POC_ESCAPE, $05, $05
charmap "벧", HANGUL_POC_ESCAPE, $05, $06
charmap "벨", HANGUL_POC_ESCAPE, $05, $07
charmap "벰", HANGUL_POC_ESCAPE, $05, $08
charmap "벱", HANGUL_POC_ESCAPE, $05, $09
charmap "벳", HANGUL_POC_ESCAPE, $05, $0a
charmap "벴", HANGUL_POC_ESCAPE, $05, $0b
charmap "벵", HANGUL_POC_ESCAPE, $05, $0c
charmap "벼", HANGUL_POC_ESCAPE, $05, $0d
charmap "벽", HANGUL_POC_ESCAPE, $05, $0e
charmap "변", HANGUL_POC_ESCAPE, $05, $0f
charmap "별", HANGUL_POC_ESCAPE, $05, $10
charmap "볍", HANGUL_POC_ESCAPE, $05, $11
charmap "볏", HANGUL_POC_ESCAPE, $05, $12
charmap "볐", HANGUL_POC_ESCAPE, $05, $13
charmap "병", HANGUL_POC_ESCAPE, $05, $14
charmap "볕", HANGUL_POC_ESCAPE, $05, $15
charmap "볘", HANGUL_POC_ESCAPE, $05, $16
charmap "볜", HANGUL_POC_ESCAPE, $05, $17
charmap "보", HANGUL_POC_ESCAPE, $05, $18
charmap "복", HANGUL_POC_ESCAPE, $05, $19
charmap "볶", HANGUL_POC_ESCAPE, $05, $1a
charmap "본", HANGUL_POC_ESCAPE, $05, $1b
charmap "볼", HANGUL_POC_ESCAPE, $05, $1c
charmap "봄", HANGUL_POC_ESCAPE, $05, $1d
charmap "봅", HANGUL_POC_ESCAPE, $05, $1e
charmap "봇", HANGUL_POC_ESCAPE, $05, $1f
charmap "봉", HANGUL_POC_ESCAPE, $05, $20
charmap "봐", HANGUL_POC_ESCAPE, $05, $21
charmap "봔", HANGUL_POC_ESCAPE, $05, $22
charmap "봤", HANGUL_POC_ESCAPE, $05, $23
charmap "봬", HANGUL_POC_ESCAPE, $05, $24
charmap "뵀", HANGUL_POC_ESCAPE, $05, $25
charmap "뵈", HANGUL_POC_ESCAPE, $05, $26
charmap "뵉", HANGUL_POC_ESCAPE, $05, $27
charmap "뵌", HANGUL_POC_ESCAPE, $05, $28
charmap "뵐", HANGUL_POC_ESCAPE, $05, $29
charmap "뵘", HANGUL_POC_ESCAPE, $05, $2a
charmap "뵙", HANGUL_POC_ESCAPE, $05, $2b
charmap "뵤", HANGUL_POC_ESCAPE, $05, $2c
charmap "뵨", HANGUL_POC_ESCAPE, $05, $2d
charmap "부", HANGUL_POC_ESCAPE, $05, $2e
charmap "북", HANGUL_POC_ESCAPE, $05, $2f
charmap "분", HANGUL_POC_ESCAPE, $05, $30
charmap "붇", HANGUL_POC_ESCAPE, $05, $31
charmap "불", HANGUL_POC_ESCAPE, $05, $32
charmap "붉", HANGUL_POC_ESCAPE, $05, $33
charmap "붊", HANGUL_POC_ESCAPE, $05, $34
charmap "붐", HANGUL_POC_ESCAPE, $05, $35
charmap "붑", HANGUL_POC_ESCAPE, $05, $36
charmap "붓", HANGUL_POC_ESCAPE, $05, $37
charmap "붕", HANGUL_POC_ESCAPE, $05, $38
charmap "붙", HANGUL_POC_ESCAPE, $05, $39
charmap "붚", HANGUL_POC_ESCAPE, $05, $3a
charmap "붜", HANGUL_POC_ESCAPE, $05, $3b
charmap "붤", HANGUL_POC_ESCAPE, $05, $3c
charmap "붰", HANGUL_POC_ESCAPE, $05, $3d
charmap "붸", HANGUL_POC_ESCAPE, $05, $3e
charmap "뷔", HANGUL_POC_ESCAPE, $05, $3f
charmap "뷕", HANGUL_POC_ESCAPE, $05, $40
charmap "뷘", HANGUL_POC_ESCAPE, $05, $41
charmap "뷜", HANGUL_POC_ESCAPE, $05, $42
charmap "뷩", HANGUL_POC_ESCAPE, $05, $43
charmap "뷰", HANGUL_POC_ESCAPE, $05, $44
charmap "뷴", HANGUL_POC_ESCAPE, $05, $45
charmap "뷸", HANGUL_POC_ESCAPE, $05, $46
charmap "븀", HANGUL_POC_ESCAPE, $05, $47
charmap "븃", HANGUL_POC_ESCAPE, $05, $48
charmap "븅", HANGUL_POC_ESCAPE, $05, $49
charmap "브", HANGUL_POC_ESCAPE, $05, $4a
charmap "븍", HANGUL_POC_ESCAPE, $05, $4b
charmap "븐", HANGUL_POC_ESCAPE, $05, $4c
charmap "블", HANGUL_POC_ESCAPE, $05, $4d
charmap "븜", HANGUL_POC_ESCAPE, $05, $4e
charmap "븝", HANGUL_POC_ESCAPE, $05, $4f
charmap "븟", HANGUL_POC_ESCAPE, $05, $60
charmap "비", HANGUL_POC_ESCAPE, $05, $61
charmap "빅", HANGUL_POC_ESCAPE, $05, $62
charmap "빈", HANGUL_POC_ESCAPE, $05, $63
charmap "빌", HANGUL_POC_ESCAPE, $05, $64
charmap "빎", HANGUL_POC_ESCAPE, $05, $65
charmap "빔", HANGUL_POC_ESCAPE, $05, $66
charmap "빕", HANGUL_POC_ESCAPE, $05, $67
charmap "빗", HANGUL_POC_ESCAPE, $05, $68
charmap "빙", HANGUL_POC_ESCAPE, $05, $69
charmap "빚", HANGUL_POC_ESCAPE, $05, $6a
charmap "빛", HANGUL_POC_ESCAPE, $05, $6b
charmap "빠", HANGUL_POC_ESCAPE, $05, $6c
charmap "빡", HANGUL_POC_ESCAPE, $05, $6d
charmap "빤", HANGUL_POC_ESCAPE, $05, $6e
charmap "빨", HANGUL_POC_ESCAPE, $05, $71
charmap "빪", HANGUL_POC_ESCAPE, $05, $72
charmap "빰", HANGUL_POC_ESCAPE, $05, $73
charmap "빱", HANGUL_POC_ESCAPE, $05, $74
charmap "빳", HANGUL_POC_ESCAPE, $05, $75
charmap "빴", HANGUL_POC_ESCAPE, $05, $76
charmap "빵", HANGUL_POC_ESCAPE, $05, $77
charmap "빻", HANGUL_POC_ESCAPE, $05, $78
charmap "빼", HANGUL_POC_ESCAPE, $05, $79
charmap "빽", HANGUL_POC_ESCAPE, $05, $7a
charmap "뺀", HANGUL_POC_ESCAPE, $05, $7b
charmap "뺄", HANGUL_POC_ESCAPE, $05, $7c
charmap "뺌", HANGUL_POC_ESCAPE, $05, $7d
charmap "뺍", HANGUL_POC_ESCAPE, $05, $7e
charmap "뺏", HANGUL_POC_ESCAPE, $05, $7f
charmap "뺐", HANGUL_POC_ESCAPE, $05, $80
charmap "뺑", HANGUL_POC_ESCAPE, $05, $81
charmap "뺘", HANGUL_POC_ESCAPE, $05, $82
charmap "뺙", HANGUL_POC_ESCAPE, $05, $83
charmap "뺨", HANGUL_POC_ESCAPE, $05, $84
charmap "뻐", HANGUL_POC_ESCAPE, $05, $85
charmap "뻑", HANGUL_POC_ESCAPE, $05, $86
charmap "뻔", HANGUL_POC_ESCAPE, $05, $87
charmap "뻗", HANGUL_POC_ESCAPE, $05, $88
charmap "뻘", HANGUL_POC_ESCAPE, $05, $89
charmap "뻠", HANGUL_POC_ESCAPE, $05, $8a
charmap "뻣", HANGUL_POC_ESCAPE, $05, $8b
charmap "뻤", HANGUL_POC_ESCAPE, $05, $8c
charmap "뻥", HANGUL_POC_ESCAPE, $05, $8d
charmap "뻬", HANGUL_POC_ESCAPE, $05, $8e
charmap "뼁", HANGUL_POC_ESCAPE, $05, $8f
charmap "뼈", HANGUL_POC_ESCAPE, $05, $90
charmap "뼉", HANGUL_POC_ESCAPE, $05, $91
charmap "뼘", HANGUL_POC_ESCAPE, $05, $92
charmap "뼙", HANGUL_POC_ESCAPE, $05, $93
charmap "뼛", HANGUL_POC_ESCAPE, $05, $94
charmap "뼜", HANGUL_POC_ESCAPE, $05, $95
charmap "뼝", HANGUL_POC_ESCAPE, $05, $96
charmap "뽀", HANGUL_POC_ESCAPE, $05, $97
charmap "뽁", HANGUL_POC_ESCAPE, $05, $98
charmap "뽄", HANGUL_POC_ESCAPE, $05, $99
charmap "뽈", HANGUL_POC_ESCAPE, $05, $9a
charmap "뽐", HANGUL_POC_ESCAPE, $05, $9b
charmap "뽑", HANGUL_POC_ESCAPE, $05, $9c
charmap "뽕", HANGUL_POC_ESCAPE, $05, $9d
charmap "뾔", HANGUL_POC_ESCAPE, $05, $9e
charmap "뾰", HANGUL_POC_ESCAPE, $05, $9f
charmap "뿅", HANGUL_POC_ESCAPE, $05, $a0
charmap "뿌", HANGUL_POC_ESCAPE, $05, $a1
charmap "뿍", HANGUL_POC_ESCAPE, $05, $a2
charmap "뿐", HANGUL_POC_ESCAPE, $05, $a3
charmap "뿔", HANGUL_POC_ESCAPE, $05, $a4
charmap "뿜", HANGUL_POC_ESCAPE, $05, $a5
charmap "뿟", HANGUL_POC_ESCAPE, $05, $a6
charmap "뿡", HANGUL_POC_ESCAPE, $05, $a7
charmap "쀼", HANGUL_POC_ESCAPE, $05, $a8
charmap "쁑", HANGUL_POC_ESCAPE, $05, $a9
charmap "쁘", HANGUL_POC_ESCAPE, $05, $aa
charmap "쁜", HANGUL_POC_ESCAPE, $05, $ab
charmap "쁠", HANGUL_POC_ESCAPE, $05, $ac
charmap "쁨", HANGUL_POC_ESCAPE, $05, $ad
charmap "쁩", HANGUL_POC_ESCAPE, $05, $ae
charmap "삐", HANGUL_POC_ESCAPE, $05, $af
charmap "삑", HANGUL_POC_ESCAPE, $05, $b0
charmap "삔", HANGUL_POC_ESCAPE, $05, $b1
charmap "삘", HANGUL_POC_ESCAPE, $05, $b2
charmap "삠", HANGUL_POC_ESCAPE, $05, $b3
charmap "삡", HANGUL_POC_ESCAPE, $05, $b4
charmap "삣", HANGUL_POC_ESCAPE, $05, $b5
charmap "삥", HANGUL_POC_ESCAPE, $05, $b6
charmap "사", HANGUL_POC_ESCAPE, $05, $b7
charmap "삭", HANGUL_POC_ESCAPE, $05, $b8
charmap "삯", HANGUL_POC_ESCAPE, $05, $b9
charmap "산", HANGUL_POC_ESCAPE, $05, $ba
charmap "삳", HANGUL_POC_ESCAPE, $05, $bb
charmap "살", HANGUL_POC_ESCAPE, $05, $bc
charmap "삵", HANGUL_POC_ESCAPE, $05, $bd
charmap "삶", HANGUL_POC_ESCAPE, $05, $be
charmap "삼", HANGUL_POC_ESCAPE, $05, $bf
charmap "삽", HANGUL_POC_ESCAPE, $05, $c0
charmap "삿", HANGUL_POC_ESCAPE, $05, $c1
charmap "샀", HANGUL_POC_ESCAPE, $05, $c2
charmap "상", HANGUL_POC_ESCAPE, $05, $c3
charmap "샅", HANGUL_POC_ESCAPE, $05, $c4
charmap "새", HANGUL_POC_ESCAPE, $05, $c5
charmap "색", HANGUL_POC_ESCAPE, $05, $c6
charmap "샌", HANGUL_POC_ESCAPE, $05, $c7
charmap "샐", HANGUL_POC_ESCAPE, $05, $c8
charmap "샘", HANGUL_POC_ESCAPE, $05, $c9
charmap "샙", HANGUL_POC_ESCAPE, $05, $ca
charmap "샛", HANGUL_POC_ESCAPE, $05, $cb
charmap "샜", HANGUL_POC_ESCAPE, $05, $cc
charmap "생", HANGUL_POC_ESCAPE, $05, $cd
charmap "샤", HANGUL_POC_ESCAPE, $05, $ce
charmap "샥", HANGUL_POC_ESCAPE, $05, $d1
charmap "샨", HANGUL_POC_ESCAPE, $05, $d2
charmap "샬", HANGUL_POC_ESCAPE, $05, $d3
charmap "샴", HANGUL_POC_ESCAPE, $05, $d4
charmap "샵", HANGUL_POC_ESCAPE, $05, $d5
charmap "샷", HANGUL_POC_ESCAPE, $05, $d6
charmap "샹", HANGUL_POC_ESCAPE, $05, $d7
charmap "섀", HANGUL_POC_ESCAPE, $05, $d8
charmap "섄", HANGUL_POC_ESCAPE, $05, $d9
charmap "섈", HANGUL_POC_ESCAPE, $05, $da
charmap "섐", HANGUL_POC_ESCAPE, $05, $db
charmap "섕", HANGUL_POC_ESCAPE, $05, $dc
charmap "서", HANGUL_POC_ESCAPE, $05, $dd
charmap "석", HANGUL_POC_ESCAPE, $05, $de
charmap "섞", HANGUL_POC_ESCAPE, $05, $df
charmap "섟", HANGUL_POC_ESCAPE, $05, $e0
charmap "선", HANGUL_POC_ESCAPE, $05, $e1
charmap "섣", HANGUL_POC_ESCAPE, $05, $e2
charmap "설", HANGUL_POC_ESCAPE, $05, $e3
charmap "섦", HANGUL_POC_ESCAPE, $05, $e4
charmap "섧", HANGUL_POC_ESCAPE, $05, $e5
charmap "섬", HANGUL_POC_ESCAPE, $05, $e6
charmap "섭", HANGUL_POC_ESCAPE, $05, $e7
charmap "섯", HANGUL_POC_ESCAPE, $05, $e8
charmap "섰", HANGUL_POC_ESCAPE, $05, $e9
charmap "성", HANGUL_POC_ESCAPE, $05, $ea
charmap "섶", HANGUL_POC_ESCAPE, $05, $eb
charmap "세", HANGUL_POC_ESCAPE, $05, $ec
charmap "섹", HANGUL_POC_ESCAPE, $05, $ed
charmap "센", HANGUL_POC_ESCAPE, $05, $ee
charmap "셀", HANGUL_POC_ESCAPE, $05, $ef
charmap "셈", HANGUL_POC_ESCAPE, $05, $f0
charmap "셉", HANGUL_POC_ESCAPE, $05, $f1
charmap "셋", HANGUL_POC_ESCAPE, $05, $f2
charmap "셌", HANGUL_POC_ESCAPE, $05, $f3
charmap "셍", HANGUL_POC_ESCAPE, $05, $f4
charmap "셔", HANGUL_POC_ESCAPE, $05, $f5
charmap "셕", HANGUL_POC_ESCAPE, $05, $f6
charmap "션", HANGUL_POC_ESCAPE, $05, $f7
charmap "셜", HANGUL_POC_ESCAPE, $05, $f8
charmap "셤", HANGUL_POC_ESCAPE, $05, $f9
charmap "셥", HANGUL_POC_ESCAPE, $05, $fa
charmap "셧", HANGUL_POC_ESCAPE, $05, $fb
charmap "셨", HANGUL_POC_ESCAPE, $05, $fc
charmap "셩", HANGUL_POC_ESCAPE, $05, $fd
charmap "셰", HANGUL_POC_ESCAPE, $05, $fe
charmap "셴", HANGUL_POC_ESCAPE, $05, $ff
charmap "셸", HANGUL_POC_ESCAPE, $06, $00
charmap "솅", HANGUL_POC_ESCAPE, $06, $01
charmap "소", HANGUL_POC_ESCAPE, $06, $02
charmap "속", HANGUL_POC_ESCAPE, $06, $03
charmap "솎", HANGUL_POC_ESCAPE, $06, $04
charmap "손", HANGUL_POC_ESCAPE, $06, $05
charmap "솔", HANGUL_POC_ESCAPE, $06, $06
charmap "솖", HANGUL_POC_ESCAPE, $06, $07
charmap "솜", HANGUL_POC_ESCAPE, $06, $08
charmap "솝", HANGUL_POC_ESCAPE, $06, $09
charmap "솟", HANGUL_POC_ESCAPE, $06, $0a
charmap "송", HANGUL_POC_ESCAPE, $06, $0b
charmap "솥", HANGUL_POC_ESCAPE, $06, $0c
charmap "솨", HANGUL_POC_ESCAPE, $06, $0d
charmap "솩", HANGUL_POC_ESCAPE, $06, $0e
charmap "솬", HANGUL_POC_ESCAPE, $06, $0f
charmap "솰", HANGUL_POC_ESCAPE, $06, $10
charmap "솽", HANGUL_POC_ESCAPE, $06, $11
charmap "쇄", HANGUL_POC_ESCAPE, $06, $12
charmap "쇈", HANGUL_POC_ESCAPE, $06, $13
charmap "쇌", HANGUL_POC_ESCAPE, $06, $14
charmap "쇔", HANGUL_POC_ESCAPE, $06, $15
charmap "쇗", HANGUL_POC_ESCAPE, $06, $16
charmap "쇘", HANGUL_POC_ESCAPE, $06, $17
charmap "쇠", HANGUL_POC_ESCAPE, $06, $18
charmap "쇤", HANGUL_POC_ESCAPE, $06, $19
charmap "쇨", HANGUL_POC_ESCAPE, $06, $1a
charmap "쇰", HANGUL_POC_ESCAPE, $06, $1b
charmap "쇱", HANGUL_POC_ESCAPE, $06, $1c
charmap "쇳", HANGUL_POC_ESCAPE, $06, $1d
charmap "쇼", HANGUL_POC_ESCAPE, $06, $1e
charmap "쇽", HANGUL_POC_ESCAPE, $06, $1f
charmap "숀", HANGUL_POC_ESCAPE, $06, $20
charmap "숄", HANGUL_POC_ESCAPE, $06, $21
charmap "숌", HANGUL_POC_ESCAPE, $06, $22
charmap "숍", HANGUL_POC_ESCAPE, $06, $23
charmap "숏", HANGUL_POC_ESCAPE, $06, $24
charmap "숑", HANGUL_POC_ESCAPE, $06, $25
charmap "수", HANGUL_POC_ESCAPE, $06, $26
charmap "숙", HANGUL_POC_ESCAPE, $06, $27
charmap "순", HANGUL_POC_ESCAPE, $06, $28
charmap "숟", HANGUL_POC_ESCAPE, $06, $29
charmap "술", HANGUL_POC_ESCAPE, $06, $2a
charmap "숨", HANGUL_POC_ESCAPE, $06, $2b
charmap "숩", HANGUL_POC_ESCAPE, $06, $2c
charmap "숫", HANGUL_POC_ESCAPE, $06, $2d
charmap "숭", HANGUL_POC_ESCAPE, $06, $2e
charmap "쌰", HANGUL_POC_ESCAPE, $06, $2f
charmap "쎼", HANGUL_POC_ESCAPE, $06, $30
charmap "숯", HANGUL_POC_ESCAPE, $06, $31
charmap "숱", HANGUL_POC_ESCAPE, $06, $32
charmap "숲", HANGUL_POC_ESCAPE, $06, $33
charmap "숴", HANGUL_POC_ESCAPE, $06, $34
charmap "쉈", HANGUL_POC_ESCAPE, $06, $35
charmap "쉐", HANGUL_POC_ESCAPE, $06, $36
charmap "쉑", HANGUL_POC_ESCAPE, $06, $37
charmap "쉔", HANGUL_POC_ESCAPE, $06, $38
charmap "쉘", HANGUL_POC_ESCAPE, $06, $39
charmap "쉠", HANGUL_POC_ESCAPE, $06, $3a
charmap "쉥", HANGUL_POC_ESCAPE, $06, $3b
charmap "쉬", HANGUL_POC_ESCAPE, $06, $3c
charmap "쉭", HANGUL_POC_ESCAPE, $06, $3d
charmap "쉰", HANGUL_POC_ESCAPE, $06, $3e
charmap "쉴", HANGUL_POC_ESCAPE, $06, $3f
charmap "쉼", HANGUL_POC_ESCAPE, $06, $40
charmap "쉽", HANGUL_POC_ESCAPE, $06, $41
charmap "쉿", HANGUL_POC_ESCAPE, $06, $42
charmap "슁", HANGUL_POC_ESCAPE, $06, $43
charmap "슈", HANGUL_POC_ESCAPE, $06, $44
charmap "슉", HANGUL_POC_ESCAPE, $06, $45
charmap "슐", HANGUL_POC_ESCAPE, $06, $46
charmap "슘", HANGUL_POC_ESCAPE, $06, $47
charmap "슛", HANGUL_POC_ESCAPE, $06, $48
charmap "슝", HANGUL_POC_ESCAPE, $06, $49
charmap "스", HANGUL_POC_ESCAPE, $06, $4a
charmap "슥", HANGUL_POC_ESCAPE, $06, $4b
charmap "슨", HANGUL_POC_ESCAPE, $06, $4c
charmap "슬", HANGUL_POC_ESCAPE, $06, $4d
charmap "슭", HANGUL_POC_ESCAPE, $06, $4e
charmap "슴", HANGUL_POC_ESCAPE, $06, $4f
charmap "습", HANGUL_POC_ESCAPE, $06, $60
charmap "슷", HANGUL_POC_ESCAPE, $06, $61
charmap "승", HANGUL_POC_ESCAPE, $06, $62
charmap "시", HANGUL_POC_ESCAPE, $06, $63
charmap "식", HANGUL_POC_ESCAPE, $06, $64
charmap "신", HANGUL_POC_ESCAPE, $06, $65
charmap "싣", HANGUL_POC_ESCAPE, $06, $66
charmap "실", HANGUL_POC_ESCAPE, $06, $67
charmap "싫", HANGUL_POC_ESCAPE, $06, $68
charmap "심", HANGUL_POC_ESCAPE, $06, $69
charmap "십", HANGUL_POC_ESCAPE, $06, $6a
charmap "싯", HANGUL_POC_ESCAPE, $06, $6b
charmap "싱", HANGUL_POC_ESCAPE, $06, $6c
charmap "싶", HANGUL_POC_ESCAPE, $06, $6d
charmap "싸", HANGUL_POC_ESCAPE, $06, $6e
charmap "싹", HANGUL_POC_ESCAPE, $06, $6f
charmap "싻", HANGUL_POC_ESCAPE, $06, $70
charmap "싼", HANGUL_POC_ESCAPE, $06, $71
charmap "쌀", HANGUL_POC_ESCAPE, $06, $72
charmap "쌈", HANGUL_POC_ESCAPE, $06, $73
charmap "쌉", HANGUL_POC_ESCAPE, $06, $74
charmap "쌌", HANGUL_POC_ESCAPE, $06, $75
charmap "쌍", HANGUL_POC_ESCAPE, $06, $76
charmap "쌓", HANGUL_POC_ESCAPE, $06, $77
charmap "쌔", HANGUL_POC_ESCAPE, $06, $78
charmap "쌕", HANGUL_POC_ESCAPE, $06, $79
charmap "쌘", HANGUL_POC_ESCAPE, $06, $7a
charmap "쌜", HANGUL_POC_ESCAPE, $06, $7b
charmap "쌤", HANGUL_POC_ESCAPE, $06, $7c
charmap "쌥", HANGUL_POC_ESCAPE, $06, $7d
charmap "쌨", HANGUL_POC_ESCAPE, $06, $7e
charmap "쌩", HANGUL_POC_ESCAPE, $06, $7f
charmap "썅", HANGUL_POC_ESCAPE, $06, $80
charmap "써", HANGUL_POC_ESCAPE, $06, $81
charmap "썩", HANGUL_POC_ESCAPE, $06, $82
charmap "썬", HANGUL_POC_ESCAPE, $06, $83
charmap "썰", HANGUL_POC_ESCAPE, $06, $84
charmap "썲", HANGUL_POC_ESCAPE, $06, $85
charmap "썸", HANGUL_POC_ESCAPE, $06, $86
charmap "썹", HANGUL_POC_ESCAPE, $06, $87
charmap "썼", HANGUL_POC_ESCAPE, $06, $88
charmap "썽", HANGUL_POC_ESCAPE, $06, $89
charmap "쎄", HANGUL_POC_ESCAPE, $06, $8a
charmap "쎈", HANGUL_POC_ESCAPE, $06, $8b
charmap "쎌", HANGUL_POC_ESCAPE, $06, $8c
charmap "쏀", HANGUL_POC_ESCAPE, $06, $8d
charmap "쏘", HANGUL_POC_ESCAPE, $06, $8e
charmap "쏙", HANGUL_POC_ESCAPE, $06, $8f
charmap "쏜", HANGUL_POC_ESCAPE, $06, $90
charmap "쏟", HANGUL_POC_ESCAPE, $06, $91
charmap "쏠", HANGUL_POC_ESCAPE, $06, $92
charmap "쏢", HANGUL_POC_ESCAPE, $06, $93
charmap "쏨", HANGUL_POC_ESCAPE, $06, $94
charmap "쏩", HANGUL_POC_ESCAPE, $06, $95
charmap "쏭", HANGUL_POC_ESCAPE, $06, $96
charmap "쏴", HANGUL_POC_ESCAPE, $06, $97
charmap "쏵", HANGUL_POC_ESCAPE, $06, $98
charmap "쏸", HANGUL_POC_ESCAPE, $06, $99
charmap "쐈", HANGUL_POC_ESCAPE, $06, $9a
charmap "쐐", HANGUL_POC_ESCAPE, $06, $9b
charmap "쐤", HANGUL_POC_ESCAPE, $06, $9c
charmap "쐬", HANGUL_POC_ESCAPE, $06, $9d
charmap "쐰", HANGUL_POC_ESCAPE, $06, $9e
charmap "쓔", HANGUL_POC_ESCAPE, $06, $a0
charmap "쐴", HANGUL_POC_ESCAPE, $06, $a1
charmap "쐼", HANGUL_POC_ESCAPE, $06, $a2
charmap "쐽", HANGUL_POC_ESCAPE, $06, $a3
charmap "쑈", HANGUL_POC_ESCAPE, $06, $a4
charmap "쑤", HANGUL_POC_ESCAPE, $06, $a5
charmap "쑥", HANGUL_POC_ESCAPE, $06, $a6
charmap "쑨", HANGUL_POC_ESCAPE, $06, $a7
charmap "쑬", HANGUL_POC_ESCAPE, $06, $a8
charmap "쑴", HANGUL_POC_ESCAPE, $06, $a9
charmap "쑵", HANGUL_POC_ESCAPE, $06, $aa
charmap "쑹", HANGUL_POC_ESCAPE, $06, $ab
charmap "쒀", HANGUL_POC_ESCAPE, $06, $ac
charmap "쒔", HANGUL_POC_ESCAPE, $06, $ad
charmap "쒜", HANGUL_POC_ESCAPE, $06, $ae
charmap "쒸", HANGUL_POC_ESCAPE, $06, $af
charmap "쒼", HANGUL_POC_ESCAPE, $06, $b0
charmap "쓩", HANGUL_POC_ESCAPE, $06, $b1
charmap "쓰", HANGUL_POC_ESCAPE, $06, $b2
charmap "쓱", HANGUL_POC_ESCAPE, $06, $b3
charmap "쓴", HANGUL_POC_ESCAPE, $06, $b4
charmap "쓸", HANGUL_POC_ESCAPE, $06, $b5
charmap "쓺", HANGUL_POC_ESCAPE, $06, $b6
charmap "쓿", HANGUL_POC_ESCAPE, $06, $b7
charmap "씀", HANGUL_POC_ESCAPE, $06, $b8
charmap "씁", HANGUL_POC_ESCAPE, $06, $b9
charmap "씌", HANGUL_POC_ESCAPE, $06, $ba
charmap "씐", HANGUL_POC_ESCAPE, $06, $bb
charmap "씔", HANGUL_POC_ESCAPE, $06, $bc
charmap "씜", HANGUL_POC_ESCAPE, $06, $bd
charmap "씨", HANGUL_POC_ESCAPE, $06, $be
charmap "씩", HANGUL_POC_ESCAPE, $06, $bf
charmap "씬", HANGUL_POC_ESCAPE, $06, $c0
charmap "씰", HANGUL_POC_ESCAPE, $06, $c1
charmap "씸", HANGUL_POC_ESCAPE, $06, $c2
charmap "씹", HANGUL_POC_ESCAPE, $06, $c3
charmap "씻", HANGUL_POC_ESCAPE, $06, $c4
charmap "씽", HANGUL_POC_ESCAPE, $06, $c5
charmap "아", HANGUL_POC_ESCAPE, $06, $c6
charmap "악", HANGUL_POC_ESCAPE, $06, $c7
charmap "안", HANGUL_POC_ESCAPE, $06, $c8
charmap "앉", HANGUL_POC_ESCAPE, $06, $c9
charmap "않", HANGUL_POC_ESCAPE, $06, $ca
charmap "알", HANGUL_POC_ESCAPE, $06, $cb
charmap "앍", HANGUL_POC_ESCAPE, $06, $cc
charmap "앎", HANGUL_POC_ESCAPE, $06, $cd
charmap "앓", HANGUL_POC_ESCAPE, $06, $ce
charmap "암", HANGUL_POC_ESCAPE, $06, $cf
charmap "압", HANGUL_POC_ESCAPE, $06, $d0
charmap "앗", HANGUL_POC_ESCAPE, $06, $d1
charmap "았", HANGUL_POC_ESCAPE, $06, $d2
charmap "앙", HANGUL_POC_ESCAPE, $06, $d3
charmap "앝", HANGUL_POC_ESCAPE, $06, $d4
charmap "앞", HANGUL_POC_ESCAPE, $06, $d5
charmap "애", HANGUL_POC_ESCAPE, $06, $d6
charmap "액", HANGUL_POC_ESCAPE, $06, $d7
charmap "앤", HANGUL_POC_ESCAPE, $06, $d8
charmap "앨", HANGUL_POC_ESCAPE, $06, $d9
charmap "앰", HANGUL_POC_ESCAPE, $06, $da
charmap "앱", HANGUL_POC_ESCAPE, $06, $db
charmap "앳", HANGUL_POC_ESCAPE, $06, $dc
charmap "앴", HANGUL_POC_ESCAPE, $06, $dd
charmap "앵", HANGUL_POC_ESCAPE, $06, $de
charmap "야", HANGUL_POC_ESCAPE, $06, $df
charmap "약", HANGUL_POC_ESCAPE, $06, $e0
charmap "얀", HANGUL_POC_ESCAPE, $06, $e1
charmap "얄", HANGUL_POC_ESCAPE, $06, $e2
charmap "얇", HANGUL_POC_ESCAPE, $06, $e3
charmap "얌", HANGUL_POC_ESCAPE, $06, $e4
charmap "얍", HANGUL_POC_ESCAPE, $06, $e5
charmap "얏", HANGUL_POC_ESCAPE, $06, $e6
charmap "양", HANGUL_POC_ESCAPE, $06, $e7
charmap "얕", HANGUL_POC_ESCAPE, $06, $e8
charmap "얗", HANGUL_POC_ESCAPE, $06, $e9
charmap "얘", HANGUL_POC_ESCAPE, $06, $ea
charmap "얜", HANGUL_POC_ESCAPE, $06, $eb
charmap "얠", HANGUL_POC_ESCAPE, $06, $ec
charmap "얩", HANGUL_POC_ESCAPE, $06, $ed
charmap "어", HANGUL_POC_ESCAPE, $06, $ee
charmap "억", HANGUL_POC_ESCAPE, $06, $ef
charmap "언", HANGUL_POC_ESCAPE, $06, $f0
charmap "얹", HANGUL_POC_ESCAPE, $06, $f1
charmap "얻", HANGUL_POC_ESCAPE, $06, $f2
charmap "얼", HANGUL_POC_ESCAPE, $06, $f3
charmap "얽", HANGUL_POC_ESCAPE, $06, $f4
charmap "얾", HANGUL_POC_ESCAPE, $06, $f5
charmap "엄", HANGUL_POC_ESCAPE, $06, $f6
charmap "업", HANGUL_POC_ESCAPE, $06, $f7
charmap "없", HANGUL_POC_ESCAPE, $06, $f8
charmap "엇", HANGUL_POC_ESCAPE, $06, $f9
charmap "었", HANGUL_POC_ESCAPE, $06, $fa
charmap "엉", HANGUL_POC_ESCAPE, $06, $fb
charmap "엊", HANGUL_POC_ESCAPE, $06, $fc
charmap "엌", HANGUL_POC_ESCAPE, $06, $fd
charmap "엎", HANGUL_POC_ESCAPE, $06, $fe
charmap "에", HANGUL_POC_ESCAPE, $07, $01
charmap "엑", HANGUL_POC_ESCAPE, $07, $02
charmap "엔", HANGUL_POC_ESCAPE, $07, $03
charmap "엘", HANGUL_POC_ESCAPE, $07, $04
charmap "엠", HANGUL_POC_ESCAPE, $07, $05
charmap "엡", HANGUL_POC_ESCAPE, $07, $06
charmap "엣", HANGUL_POC_ESCAPE, $07, $07
charmap "엥", HANGUL_POC_ESCAPE, $07, $08
charmap "여", HANGUL_POC_ESCAPE, $07, $09
charmap "역", HANGUL_POC_ESCAPE, $07, $0a
charmap "엮", HANGUL_POC_ESCAPE, $07, $0b
charmap "연", HANGUL_POC_ESCAPE, $07, $0c
charmap "열", HANGUL_POC_ESCAPE, $07, $0d
charmap "엶", HANGUL_POC_ESCAPE, $07, $0e
charmap "엷", HANGUL_POC_ESCAPE, $07, $0f
charmap "염", HANGUL_POC_ESCAPE, $07, $10
charmap "엽", HANGUL_POC_ESCAPE, $07, $11
charmap "엾", HANGUL_POC_ESCAPE, $07, $12
charmap "엿", HANGUL_POC_ESCAPE, $07, $13
charmap "였", HANGUL_POC_ESCAPE, $07, $14
charmap "영", HANGUL_POC_ESCAPE, $07, $15
charmap "옅", HANGUL_POC_ESCAPE, $07, $16
charmap "옆", HANGUL_POC_ESCAPE, $07, $17
charmap "옇", HANGUL_POC_ESCAPE, $07, $18
charmap "예", HANGUL_POC_ESCAPE, $07, $19
charmap "옌", HANGUL_POC_ESCAPE, $07, $1a
charmap "옐", HANGUL_POC_ESCAPE, $07, $1b
charmap "옘", HANGUL_POC_ESCAPE, $07, $1c
charmap "옙", HANGUL_POC_ESCAPE, $07, $1d
charmap "옛", HANGUL_POC_ESCAPE, $07, $1e
charmap "옜", HANGUL_POC_ESCAPE, $07, $1f
charmap "오", HANGUL_POC_ESCAPE, $07, $20
charmap "옥", HANGUL_POC_ESCAPE, $07, $21
charmap "온", HANGUL_POC_ESCAPE, $07, $22
charmap "올", HANGUL_POC_ESCAPE, $07, $23
charmap "옭", HANGUL_POC_ESCAPE, $07, $24
charmap "옮", HANGUL_POC_ESCAPE, $07, $25
charmap "옰", HANGUL_POC_ESCAPE, $07, $26
charmap "옳", HANGUL_POC_ESCAPE, $07, $27
charmap "옴", HANGUL_POC_ESCAPE, $07, $28
charmap "옵", HANGUL_POC_ESCAPE, $07, $29
charmap "옷", HANGUL_POC_ESCAPE, $07, $2a
charmap "옹", HANGUL_POC_ESCAPE, $07, $2b
charmap "옻", HANGUL_POC_ESCAPE, $07, $2c
charmap "와", HANGUL_POC_ESCAPE, $07, $2d
charmap "왁", HANGUL_POC_ESCAPE, $07, $2e
charmap "완", HANGUL_POC_ESCAPE, $07, $2f
charmap "왈", HANGUL_POC_ESCAPE, $07, $30
charmap "왐", HANGUL_POC_ESCAPE, $07, $31
charmap "왑", HANGUL_POC_ESCAPE, $07, $32
charmap "왓", HANGUL_POC_ESCAPE, $07, $33
charmap "왔", HANGUL_POC_ESCAPE, $07, $34
charmap "왕", HANGUL_POC_ESCAPE, $07, $35
charmap "왜", HANGUL_POC_ESCAPE, $07, $36
charmap "왝", HANGUL_POC_ESCAPE, $07, $37
charmap "왠", HANGUL_POC_ESCAPE, $07, $38
charmap "왬", HANGUL_POC_ESCAPE, $07, $39
charmap "왯", HANGUL_POC_ESCAPE, $07, $3a
charmap "왱", HANGUL_POC_ESCAPE, $07, $3b
charmap "외", HANGUL_POC_ESCAPE, $07, $3c
charmap "왹", HANGUL_POC_ESCAPE, $07, $3d
charmap "왼", HANGUL_POC_ESCAPE, $07, $3e
charmap "욀", HANGUL_POC_ESCAPE, $07, $3f
charmap "욈", HANGUL_POC_ESCAPE, $07, $40
charmap "욉", HANGUL_POC_ESCAPE, $07, $41
charmap "욋", HANGUL_POC_ESCAPE, $07, $42
charmap "욍", HANGUL_POC_ESCAPE, $07, $43
charmap "요", HANGUL_POC_ESCAPE, $07, $44
charmap "욕", HANGUL_POC_ESCAPE, $07, $45
charmap "욘", HANGUL_POC_ESCAPE, $07, $46
charmap "욜", HANGUL_POC_ESCAPE, $07, $47
charmap "욤", HANGUL_POC_ESCAPE, $07, $48
charmap "욥", HANGUL_POC_ESCAPE, $07, $49
charmap "욧", HANGUL_POC_ESCAPE, $07, $4a
charmap "용", HANGUL_POC_ESCAPE, $07, $4b
charmap "우", HANGUL_POC_ESCAPE, $07, $4c
charmap "욱", HANGUL_POC_ESCAPE, $07, $4d
charmap "운", HANGUL_POC_ESCAPE, $07, $4e
charmap "울", HANGUL_POC_ESCAPE, $07, $4f
charmap "욹", HANGUL_POC_ESCAPE, $07, $60
charmap "욺", HANGUL_POC_ESCAPE, $07, $61
charmap "움", HANGUL_POC_ESCAPE, $07, $62
charmap "웁", HANGUL_POC_ESCAPE, $07, $63
charmap "웃", HANGUL_POC_ESCAPE, $07, $64
charmap "웅", HANGUL_POC_ESCAPE, $07, $65
charmap "워", HANGUL_POC_ESCAPE, $07, $66
charmap "웍", HANGUL_POC_ESCAPE, $07, $67
charmap "원", HANGUL_POC_ESCAPE, $07, $68
charmap "월", HANGUL_POC_ESCAPE, $07, $69
charmap "웜", HANGUL_POC_ESCAPE, $07, $6a
charmap "웝", HANGUL_POC_ESCAPE, $07, $6b
charmap "웠", HANGUL_POC_ESCAPE, $07, $6c
charmap "웡", HANGUL_POC_ESCAPE, $07, $6d
charmap "웨", HANGUL_POC_ESCAPE, $07, $6e
charmap "웩", HANGUL_POC_ESCAPE, $07, $71
charmap "웬", HANGUL_POC_ESCAPE, $07, $72
charmap "웰", HANGUL_POC_ESCAPE, $07, $73
charmap "웸", HANGUL_POC_ESCAPE, $07, $74
charmap "웹", HANGUL_POC_ESCAPE, $07, $75
charmap "웽", HANGUL_POC_ESCAPE, $07, $76
charmap "위", HANGUL_POC_ESCAPE, $07, $77
charmap "윅", HANGUL_POC_ESCAPE, $07, $78
charmap "윈", HANGUL_POC_ESCAPE, $07, $79
charmap "윌", HANGUL_POC_ESCAPE, $07, $7a
charmap "윔", HANGUL_POC_ESCAPE, $07, $7b
charmap "윕", HANGUL_POC_ESCAPE, $07, $7c
charmap "윗", HANGUL_POC_ESCAPE, $07, $7d
charmap "윙", HANGUL_POC_ESCAPE, $07, $7e
charmap "유", HANGUL_POC_ESCAPE, $07, $7f
charmap "육", HANGUL_POC_ESCAPE, $07, $80
charmap "윤", HANGUL_POC_ESCAPE, $07, $81
charmap "율", HANGUL_POC_ESCAPE, $07, $82
charmap "윰", HANGUL_POC_ESCAPE, $07, $83
charmap "윱", HANGUL_POC_ESCAPE, $07, $84
charmap "윳", HANGUL_POC_ESCAPE, $07, $85
charmap "융", HANGUL_POC_ESCAPE, $07, $86
charmap "윷", HANGUL_POC_ESCAPE, $07, $87
charmap "으", HANGUL_POC_ESCAPE, $07, $88
charmap "윽", HANGUL_POC_ESCAPE, $07, $89
charmap "은", HANGUL_POC_ESCAPE, $07, $8a
charmap "을", HANGUL_POC_ESCAPE, $07, $8b
charmap "읆", HANGUL_POC_ESCAPE, $07, $8c
charmap "음", HANGUL_POC_ESCAPE, $07, $8d
charmap "읍", HANGUL_POC_ESCAPE, $07, $8e
charmap "읏", HANGUL_POC_ESCAPE, $07, $8f
charmap "응", HANGUL_POC_ESCAPE, $07, $90
charmap "읒", HANGUL_POC_ESCAPE, $07, $91
charmap "읓", HANGUL_POC_ESCAPE, $07, $92
charmap "읔", HANGUL_POC_ESCAPE, $07, $93
charmap "읕", HANGUL_POC_ESCAPE, $07, $94
charmap "읖", HANGUL_POC_ESCAPE, $07, $95
charmap "읗", HANGUL_POC_ESCAPE, $07, $96
charmap "의", HANGUL_POC_ESCAPE, $07, $97
charmap "읜", HANGUL_POC_ESCAPE, $07, $98
charmap "읠", HANGUL_POC_ESCAPE, $07, $99
charmap "읨", HANGUL_POC_ESCAPE, $07, $9a
charmap "읫", HANGUL_POC_ESCAPE, $07, $9b
charmap "이", HANGUL_POC_ESCAPE, $07, $9c
charmap "익", HANGUL_POC_ESCAPE, $07, $9d
charmap "인", HANGUL_POC_ESCAPE, $07, $9e
charmap "일", HANGUL_POC_ESCAPE, $07, $9f
charmap "읽", HANGUL_POC_ESCAPE, $07, $a0
charmap "읾", HANGUL_POC_ESCAPE, $07, $a1
charmap "잃", HANGUL_POC_ESCAPE, $07, $a2
charmap "임", HANGUL_POC_ESCAPE, $07, $a3
charmap "입", HANGUL_POC_ESCAPE, $07, $a4
charmap "잇", HANGUL_POC_ESCAPE, $07, $a5
charmap "있", HANGUL_POC_ESCAPE, $07, $a6
charmap "잉", HANGUL_POC_ESCAPE, $07, $a7
charmap "잊", HANGUL_POC_ESCAPE, $07, $a8
charmap "잎", HANGUL_POC_ESCAPE, $07, $a9
charmap "자", HANGUL_POC_ESCAPE, $07, $aa
charmap "작", HANGUL_POC_ESCAPE, $07, $ab
charmap "잔", HANGUL_POC_ESCAPE, $07, $ac
charmap "잖", HANGUL_POC_ESCAPE, $07, $ad
charmap "잗", HANGUL_POC_ESCAPE, $07, $ae
charmap "잘", HANGUL_POC_ESCAPE, $07, $af
charmap "잚", HANGUL_POC_ESCAPE, $07, $b0
charmap "잠", HANGUL_POC_ESCAPE, $07, $b1
charmap "잡", HANGUL_POC_ESCAPE, $07, $b2
charmap "잣", HANGUL_POC_ESCAPE, $07, $b3
charmap "잤", HANGUL_POC_ESCAPE, $07, $b4
charmap "장", HANGUL_POC_ESCAPE, $07, $b5
charmap "잦", HANGUL_POC_ESCAPE, $07, $b6
charmap "재", HANGUL_POC_ESCAPE, $07, $b7
charmap "잭", HANGUL_POC_ESCAPE, $07, $b8
charmap "잰", HANGUL_POC_ESCAPE, $07, $b9
charmap "잴", HANGUL_POC_ESCAPE, $07, $ba
charmap "잼", HANGUL_POC_ESCAPE, $07, $bb
charmap "잽", HANGUL_POC_ESCAPE, $07, $bc
charmap "잿", HANGUL_POC_ESCAPE, $07, $bd
charmap "쟀", HANGUL_POC_ESCAPE, $07, $be
charmap "쟁", HANGUL_POC_ESCAPE, $07, $bf
charmap "쟈", HANGUL_POC_ESCAPE, $07, $c0
charmap "쟉", HANGUL_POC_ESCAPE, $07, $c1
charmap "쟌", HANGUL_POC_ESCAPE, $07, $c2
charmap "쟎", HANGUL_POC_ESCAPE, $07, $c3
charmap "쟐", HANGUL_POC_ESCAPE, $07, $c4
charmap "쟘", HANGUL_POC_ESCAPE, $07, $c5
charmap "쟝", HANGUL_POC_ESCAPE, $07, $c6
charmap "쟤", HANGUL_POC_ESCAPE, $07, $c7
charmap "쟨", HANGUL_POC_ESCAPE, $07, $c8
charmap "쟬", HANGUL_POC_ESCAPE, $07, $c9
charmap "저", HANGUL_POC_ESCAPE, $07, $ca
charmap "적", HANGUL_POC_ESCAPE, $07, $cb
charmap "전", HANGUL_POC_ESCAPE, $07, $cc
charmap "절", HANGUL_POC_ESCAPE, $07, $cd
charmap "젊", HANGUL_POC_ESCAPE, $07, $ce
charmap "점", HANGUL_POC_ESCAPE, $07, $d1
charmap "접", HANGUL_POC_ESCAPE, $07, $d2
charmap "젓", HANGUL_POC_ESCAPE, $07, $d3
charmap "정", HANGUL_POC_ESCAPE, $07, $d4
charmap "젖", HANGUL_POC_ESCAPE, $07, $d5
charmap "제", HANGUL_POC_ESCAPE, $07, $d6
charmap "젝", HANGUL_POC_ESCAPE, $07, $d7
charmap "젠", HANGUL_POC_ESCAPE, $07, $d8
charmap "젤", HANGUL_POC_ESCAPE, $07, $d9
charmap "젬", HANGUL_POC_ESCAPE, $07, $da
charmap "젭", HANGUL_POC_ESCAPE, $07, $db
charmap "젯", HANGUL_POC_ESCAPE, $07, $dc
charmap "젱", HANGUL_POC_ESCAPE, $07, $dd
charmap "져", HANGUL_POC_ESCAPE, $07, $de
charmap "젼", HANGUL_POC_ESCAPE, $07, $df
charmap "졀", HANGUL_POC_ESCAPE, $07, $e0
charmap "졈", HANGUL_POC_ESCAPE, $07, $e1
charmap "졉", HANGUL_POC_ESCAPE, $07, $e2
charmap "졌", HANGUL_POC_ESCAPE, $07, $e3
charmap "졍", HANGUL_POC_ESCAPE, $07, $e4
charmap "졔", HANGUL_POC_ESCAPE, $07, $e5
charmap "조", HANGUL_POC_ESCAPE, $07, $e6
charmap "족", HANGUL_POC_ESCAPE, $07, $e7
charmap "존", HANGUL_POC_ESCAPE, $07, $e8
charmap "졸", HANGUL_POC_ESCAPE, $07, $e9
charmap "졺", HANGUL_POC_ESCAPE, $07, $ea
charmap "좀", HANGUL_POC_ESCAPE, $07, $eb
charmap "좁", HANGUL_POC_ESCAPE, $07, $ec
charmap "좃", HANGUL_POC_ESCAPE, $07, $ed
charmap "종", HANGUL_POC_ESCAPE, $07, $ee
charmap "좆", HANGUL_POC_ESCAPE, $07, $ef
charmap "좇", HANGUL_POC_ESCAPE, $07, $f0
charmap "좋", HANGUL_POC_ESCAPE, $07, $f1
charmap "좌", HANGUL_POC_ESCAPE, $07, $f2
charmap "좍", HANGUL_POC_ESCAPE, $07, $f3
charmap "좔", HANGUL_POC_ESCAPE, $07, $f4
charmap "좝", HANGUL_POC_ESCAPE, $07, $f5
charmap "좟", HANGUL_POC_ESCAPE, $07, $f6
charmap "좡", HANGUL_POC_ESCAPE, $07, $f7
charmap "좨", HANGUL_POC_ESCAPE, $07, $f8
charmap "좼", HANGUL_POC_ESCAPE, $07, $f9
charmap "좽", HANGUL_POC_ESCAPE, $07, $fa
charmap "죄", HANGUL_POC_ESCAPE, $07, $fb
charmap "죈", HANGUL_POC_ESCAPE, $07, $fc
charmap "죌", HANGUL_POC_ESCAPE, $07, $fd
charmap "죔", HANGUL_POC_ESCAPE, $07, $fe
charmap "죕", HANGUL_POC_ESCAPE, $07, $ff
charmap "죗", HANGUL_POC_ESCAPE, $08, $00
charmap "죙", HANGUL_POC_ESCAPE, $08, $01
charmap "죠", HANGUL_POC_ESCAPE, $08, $02
charmap "죡", HANGUL_POC_ESCAPE, $08, $03
charmap "죤", HANGUL_POC_ESCAPE, $08, $04
charmap "죵", HANGUL_POC_ESCAPE, $08, $05
charmap "주", HANGUL_POC_ESCAPE, $08, $06
charmap "죽", HANGUL_POC_ESCAPE, $08, $07
charmap "준", HANGUL_POC_ESCAPE, $08, $08
charmap "줄", HANGUL_POC_ESCAPE, $08, $09
charmap "줅", HANGUL_POC_ESCAPE, $08, $0a
charmap "줆", HANGUL_POC_ESCAPE, $08, $0b
charmap "줌", HANGUL_POC_ESCAPE, $08, $0c
charmap "줍", HANGUL_POC_ESCAPE, $08, $0d
charmap "줏", HANGUL_POC_ESCAPE, $08, $0e
charmap "중", HANGUL_POC_ESCAPE, $08, $0f
charmap "줘", HANGUL_POC_ESCAPE, $08, $10
charmap "줬", HANGUL_POC_ESCAPE, $08, $11
charmap "줴", HANGUL_POC_ESCAPE, $08, $12
charmap "쥐", HANGUL_POC_ESCAPE, $08, $13
charmap "쥑", HANGUL_POC_ESCAPE, $08, $14
charmap "쥔", HANGUL_POC_ESCAPE, $08, $15
charmap "쥘", HANGUL_POC_ESCAPE, $08, $16
charmap "쥠", HANGUL_POC_ESCAPE, $08, $17
charmap "쥡", HANGUL_POC_ESCAPE, $08, $18
charmap "쥣", HANGUL_POC_ESCAPE, $08, $19
charmap "쥬", HANGUL_POC_ESCAPE, $08, $1a
charmap "쥰", HANGUL_POC_ESCAPE, $08, $1b
charmap "쥴", HANGUL_POC_ESCAPE, $08, $1c
charmap "쥼", HANGUL_POC_ESCAPE, $08, $1d
charmap "즈", HANGUL_POC_ESCAPE, $08, $1e
charmap "즉", HANGUL_POC_ESCAPE, $08, $1f
charmap "즌", HANGUL_POC_ESCAPE, $08, $20
charmap "즐", HANGUL_POC_ESCAPE, $08, $21
charmap "즘", HANGUL_POC_ESCAPE, $08, $22
charmap "즙", HANGUL_POC_ESCAPE, $08, $23
charmap "즛", HANGUL_POC_ESCAPE, $08, $24
charmap "증", HANGUL_POC_ESCAPE, $08, $25
charmap "지", HANGUL_POC_ESCAPE, $08, $26
charmap "직", HANGUL_POC_ESCAPE, $08, $27
charmap "진", HANGUL_POC_ESCAPE, $08, $28
charmap "짇", HANGUL_POC_ESCAPE, $08, $29
charmap "질", HANGUL_POC_ESCAPE, $08, $2a
charmap "짊", HANGUL_POC_ESCAPE, $08, $2b
charmap "짐", HANGUL_POC_ESCAPE, $08, $2c
charmap "집", HANGUL_POC_ESCAPE, $08, $2d
charmap "짓", HANGUL_POC_ESCAPE, $08, $2e
charmap "쬬", HANGUL_POC_ESCAPE, $08, $30
charmap "징", HANGUL_POC_ESCAPE, $08, $31
charmap "짖", HANGUL_POC_ESCAPE, $08, $32
charmap "짙", HANGUL_POC_ESCAPE, $08, $33
charmap "짚", HANGUL_POC_ESCAPE, $08, $34
charmap "짜", HANGUL_POC_ESCAPE, $08, $35
charmap "짝", HANGUL_POC_ESCAPE, $08, $36
charmap "짠", HANGUL_POC_ESCAPE, $08, $37
charmap "짢", HANGUL_POC_ESCAPE, $08, $38
charmap "짤", HANGUL_POC_ESCAPE, $08, $39
charmap "짧", HANGUL_POC_ESCAPE, $08, $3a
charmap "짬", HANGUL_POC_ESCAPE, $08, $3b
charmap "짭", HANGUL_POC_ESCAPE, $08, $3c
charmap "짯", HANGUL_POC_ESCAPE, $08, $3d
charmap "짰", HANGUL_POC_ESCAPE, $08, $3e
charmap "짱", HANGUL_POC_ESCAPE, $08, $3f
charmap "째", HANGUL_POC_ESCAPE, $08, $40
charmap "짹", HANGUL_POC_ESCAPE, $08, $41
charmap "짼", HANGUL_POC_ESCAPE, $08, $42
charmap "쨀", HANGUL_POC_ESCAPE, $08, $43
charmap "쨈", HANGUL_POC_ESCAPE, $08, $44
charmap "쨉", HANGUL_POC_ESCAPE, $08, $45
charmap "쨋", HANGUL_POC_ESCAPE, $08, $46
charmap "쨌", HANGUL_POC_ESCAPE, $08, $47
charmap "쨍", HANGUL_POC_ESCAPE, $08, $48
charmap "쨔", HANGUL_POC_ESCAPE, $08, $49
charmap "쨘", HANGUL_POC_ESCAPE, $08, $4a
charmap "쨩", HANGUL_POC_ESCAPE, $08, $4b
charmap "쩌", HANGUL_POC_ESCAPE, $08, $4c
charmap "쩍", HANGUL_POC_ESCAPE, $08, $4d
charmap "쩐", HANGUL_POC_ESCAPE, $08, $4e
charmap "쩔", HANGUL_POC_ESCAPE, $08, $4f
charmap "쩜", HANGUL_POC_ESCAPE, $08, $60
charmap "쩝", HANGUL_POC_ESCAPE, $08, $61
charmap "쩟", HANGUL_POC_ESCAPE, $08, $62
charmap "쩠", HANGUL_POC_ESCAPE, $08, $63
charmap "쩡", HANGUL_POC_ESCAPE, $08, $64
charmap "쩨", HANGUL_POC_ESCAPE, $08, $65
charmap "쩽", HANGUL_POC_ESCAPE, $08, $66
charmap "쪄", HANGUL_POC_ESCAPE, $08, $67
charmap "쪘", HANGUL_POC_ESCAPE, $08, $68
charmap "쪼", HANGUL_POC_ESCAPE, $08, $69
charmap "쪽", HANGUL_POC_ESCAPE, $08, $6a
charmap "쫀", HANGUL_POC_ESCAPE, $08, $6b
charmap "쫄", HANGUL_POC_ESCAPE, $08, $6c
charmap "쫌", HANGUL_POC_ESCAPE, $08, $6d
charmap "쫍", HANGUL_POC_ESCAPE, $08, $6e
charmap "쫏", HANGUL_POC_ESCAPE, $08, $6f
charmap "쫑", HANGUL_POC_ESCAPE, $08, $70
charmap "쫓", HANGUL_POC_ESCAPE, $08, $71
charmap "쫘", HANGUL_POC_ESCAPE, $08, $72
charmap "쫙", HANGUL_POC_ESCAPE, $08, $73
charmap "쫠", HANGUL_POC_ESCAPE, $08, $74
charmap "쫬", HANGUL_POC_ESCAPE, $08, $75
charmap "쫴", HANGUL_POC_ESCAPE, $08, $76
charmap "쬈", HANGUL_POC_ESCAPE, $08, $77
charmap "쬐", HANGUL_POC_ESCAPE, $08, $78
charmap "쬔", HANGUL_POC_ESCAPE, $08, $79
charmap "쬘", HANGUL_POC_ESCAPE, $08, $7a
charmap "쬠", HANGUL_POC_ESCAPE, $08, $7b
charmap "쬡", HANGUL_POC_ESCAPE, $08, $7c
charmap "쭁", HANGUL_POC_ESCAPE, $08, $7d
charmap "쭈", HANGUL_POC_ESCAPE, $08, $7e
charmap "쭉", HANGUL_POC_ESCAPE, $08, $7f
charmap "쭌", HANGUL_POC_ESCAPE, $08, $80
charmap "쭐", HANGUL_POC_ESCAPE, $08, $81
charmap "쭘", HANGUL_POC_ESCAPE, $08, $82
charmap "쭙", HANGUL_POC_ESCAPE, $08, $83
charmap "쭝", HANGUL_POC_ESCAPE, $08, $84
charmap "쭤", HANGUL_POC_ESCAPE, $08, $85
charmap "쭸", HANGUL_POC_ESCAPE, $08, $86
charmap "쭹", HANGUL_POC_ESCAPE, $08, $87
charmap "쮜", HANGUL_POC_ESCAPE, $08, $88
charmap "쮸", HANGUL_POC_ESCAPE, $08, $89
charmap "쯔", HANGUL_POC_ESCAPE, $08, $8a
charmap "쯤", HANGUL_POC_ESCAPE, $08, $8b
charmap "쯧", HANGUL_POC_ESCAPE, $08, $8c
charmap "쯩", HANGUL_POC_ESCAPE, $08, $8d
charmap "찌", HANGUL_POC_ESCAPE, $08, $8e
charmap "찍", HANGUL_POC_ESCAPE, $08, $8f
charmap "찐", HANGUL_POC_ESCAPE, $08, $90
charmap "찔", HANGUL_POC_ESCAPE, $08, $91
charmap "찜", HANGUL_POC_ESCAPE, $08, $92
charmap "찝", HANGUL_POC_ESCAPE, $08, $93
charmap "찡", HANGUL_POC_ESCAPE, $08, $94
charmap "찢", HANGUL_POC_ESCAPE, $08, $95
charmap "찧", HANGUL_POC_ESCAPE, $08, $96
charmap "차", HANGUL_POC_ESCAPE, $08, $97
charmap "착", HANGUL_POC_ESCAPE, $08, $98
charmap "찬", HANGUL_POC_ESCAPE, $08, $99
charmap "찮", HANGUL_POC_ESCAPE, $08, $9a
charmap "찰", HANGUL_POC_ESCAPE, $08, $9b
charmap "참", HANGUL_POC_ESCAPE, $08, $9c
charmap "찹", HANGUL_POC_ESCAPE, $08, $9d
charmap "찻", HANGUL_POC_ESCAPE, $08, $9e
charmap "찼", HANGUL_POC_ESCAPE, $08, $a1
charmap "창", HANGUL_POC_ESCAPE, $08, $a2
charmap "찾", HANGUL_POC_ESCAPE, $08, $a3
charmap "채", HANGUL_POC_ESCAPE, $08, $a4
charmap "책", HANGUL_POC_ESCAPE, $08, $a5
charmap "챈", HANGUL_POC_ESCAPE, $08, $a6
charmap "챌", HANGUL_POC_ESCAPE, $08, $a7
charmap "챔", HANGUL_POC_ESCAPE, $08, $a8
charmap "챕", HANGUL_POC_ESCAPE, $08, $a9
charmap "챗", HANGUL_POC_ESCAPE, $08, $aa
charmap "챘", HANGUL_POC_ESCAPE, $08, $ab
charmap "챙", HANGUL_POC_ESCAPE, $08, $ac
charmap "챠", HANGUL_POC_ESCAPE, $08, $ad
charmap "챤", HANGUL_POC_ESCAPE, $08, $ae
charmap "챦", HANGUL_POC_ESCAPE, $08, $af
charmap "챨", HANGUL_POC_ESCAPE, $08, $b0
charmap "챰", HANGUL_POC_ESCAPE, $08, $b1
charmap "챵", HANGUL_POC_ESCAPE, $08, $b2
charmap "처", HANGUL_POC_ESCAPE, $08, $b3
charmap "척", HANGUL_POC_ESCAPE, $08, $b4
charmap "천", HANGUL_POC_ESCAPE, $08, $b5
charmap "철", HANGUL_POC_ESCAPE, $08, $b6
charmap "첨", HANGUL_POC_ESCAPE, $08, $b7
charmap "첩", HANGUL_POC_ESCAPE, $08, $b8
charmap "첫", HANGUL_POC_ESCAPE, $08, $b9
charmap "첬", HANGUL_POC_ESCAPE, $08, $ba
charmap "청", HANGUL_POC_ESCAPE, $08, $bb
charmap "체", HANGUL_POC_ESCAPE, $08, $bc
charmap "첵", HANGUL_POC_ESCAPE, $08, $bd
charmap "첸", HANGUL_POC_ESCAPE, $08, $be
charmap "첼", HANGUL_POC_ESCAPE, $08, $bf
charmap "쳄", HANGUL_POC_ESCAPE, $08, $c0
charmap "쳅", HANGUL_POC_ESCAPE, $08, $c1
charmap "쳇", HANGUL_POC_ESCAPE, $08, $c2
charmap "쳉", HANGUL_POC_ESCAPE, $08, $c3
charmap "쳐", HANGUL_POC_ESCAPE, $08, $c4
charmap "쳔", HANGUL_POC_ESCAPE, $08, $c5
charmap "쳤", HANGUL_POC_ESCAPE, $08, $c6
charmap "쳬", HANGUL_POC_ESCAPE, $08, $c7
charmap "쳰", HANGUL_POC_ESCAPE, $08, $c8
charmap "촁", HANGUL_POC_ESCAPE, $08, $c9
charmap "초", HANGUL_POC_ESCAPE, $08, $ca
charmap "촉", HANGUL_POC_ESCAPE, $08, $cb
charmap "촌", HANGUL_POC_ESCAPE, $08, $cc
charmap "촐", HANGUL_POC_ESCAPE, $08, $cd
charmap "촘", HANGUL_POC_ESCAPE, $08, $ce
charmap "촙", HANGUL_POC_ESCAPE, $08, $cf
charmap "촛", HANGUL_POC_ESCAPE, $08, $d0
charmap "총", HANGUL_POC_ESCAPE, $08, $d1
charmap "촤", HANGUL_POC_ESCAPE, $08, $d2
charmap "촨", HANGUL_POC_ESCAPE, $08, $d3
charmap "촬", HANGUL_POC_ESCAPE, $08, $d4
charmap "촹", HANGUL_POC_ESCAPE, $08, $d5
charmap "최", HANGUL_POC_ESCAPE, $08, $d6
charmap "쵠", HANGUL_POC_ESCAPE, $08, $d7
charmap "쵤", HANGUL_POC_ESCAPE, $08, $d8
charmap "쵬", HANGUL_POC_ESCAPE, $08, $d9
charmap "쵭", HANGUL_POC_ESCAPE, $08, $da
charmap "쵯", HANGUL_POC_ESCAPE, $08, $db
charmap "쵱", HANGUL_POC_ESCAPE, $08, $dc
charmap "쵸", HANGUL_POC_ESCAPE, $08, $dd
charmap "춈", HANGUL_POC_ESCAPE, $08, $de
charmap "추", HANGUL_POC_ESCAPE, $08, $df
charmap "축", HANGUL_POC_ESCAPE, $08, $e0
charmap "춘", HANGUL_POC_ESCAPE, $08, $e1
charmap "춤", HANGUL_POC_ESCAPE, $08, $e3
charmap "춥", HANGUL_POC_ESCAPE, $08, $e4
charmap "춧", HANGUL_POC_ESCAPE, $08, $e5
charmap "충", HANGUL_POC_ESCAPE, $08, $e6
charmap "춰", HANGUL_POC_ESCAPE, $08, $e7
charmap "췄", HANGUL_POC_ESCAPE, $08, $e8
charmap "췌", HANGUL_POC_ESCAPE, $08, $e9
charmap "췐", HANGUL_POC_ESCAPE, $08, $ea
charmap "취", HANGUL_POC_ESCAPE, $08, $eb
charmap "췬", HANGUL_POC_ESCAPE, $08, $ec
charmap "췰", HANGUL_POC_ESCAPE, $08, $ed
charmap "췸", HANGUL_POC_ESCAPE, $08, $ee
charmap "췹", HANGUL_POC_ESCAPE, $08, $ef
charmap "췻", HANGUL_POC_ESCAPE, $08, $f0
charmap "췽", HANGUL_POC_ESCAPE, $08, $f1
charmap "츄", HANGUL_POC_ESCAPE, $08, $f2
charmap "츈", HANGUL_POC_ESCAPE, $08, $f3
charmap "츌", HANGUL_POC_ESCAPE, $08, $f4
charmap "츔", HANGUL_POC_ESCAPE, $08, $f5
charmap "츙", HANGUL_POC_ESCAPE, $08, $f6
charmap "츠", HANGUL_POC_ESCAPE, $08, $f7
charmap "측", HANGUL_POC_ESCAPE, $08, $f8
charmap "츤", HANGUL_POC_ESCAPE, $08, $f9
charmap "츨", HANGUL_POC_ESCAPE, $08, $fa
charmap "츰", HANGUL_POC_ESCAPE, $08, $fb
charmap "츱", HANGUL_POC_ESCAPE, $08, $fc
charmap "츳", HANGUL_POC_ESCAPE, $08, $fd
charmap "층", HANGUL_POC_ESCAPE, $08, $fe
charmap "치", HANGUL_POC_ESCAPE, $09, $01
charmap "칙", HANGUL_POC_ESCAPE, $09, $02
charmap "친", HANGUL_POC_ESCAPE, $09, $03
charmap "칟", HANGUL_POC_ESCAPE, $09, $04
charmap "칠", HANGUL_POC_ESCAPE, $09, $05
charmap "칡", HANGUL_POC_ESCAPE, $09, $06
charmap "침", HANGUL_POC_ESCAPE, $09, $07
charmap "칩", HANGUL_POC_ESCAPE, $09, $08
charmap "칫", HANGUL_POC_ESCAPE, $09, $09
charmap "칭", HANGUL_POC_ESCAPE, $09, $0a
charmap "카", HANGUL_POC_ESCAPE, $09, $0b
charmap "칵", HANGUL_POC_ESCAPE, $09, $0c
charmap "칸", HANGUL_POC_ESCAPE, $09, $0d
charmap "칼", HANGUL_POC_ESCAPE, $09, $0e
charmap "캄", HANGUL_POC_ESCAPE, $09, $0f
charmap "캅", HANGUL_POC_ESCAPE, $09, $10
charmap "캇", HANGUL_POC_ESCAPE, $09, $11
charmap "캉", HANGUL_POC_ESCAPE, $09, $12
charmap "캐", HANGUL_POC_ESCAPE, $09, $13
charmap "캑", HANGUL_POC_ESCAPE, $09, $14
charmap "캔", HANGUL_POC_ESCAPE, $09, $15
charmap "캘", HANGUL_POC_ESCAPE, $09, $16
charmap "캠", HANGUL_POC_ESCAPE, $09, $17
charmap "캡", HANGUL_POC_ESCAPE, $09, $18
charmap "캣", HANGUL_POC_ESCAPE, $09, $19
charmap "캤", HANGUL_POC_ESCAPE, $09, $1a
charmap "캥", HANGUL_POC_ESCAPE, $09, $1b
charmap "캬", HANGUL_POC_ESCAPE, $09, $1c
charmap "캭", HANGUL_POC_ESCAPE, $09, $1d
charmap "컁", HANGUL_POC_ESCAPE, $09, $1e
charmap "커", HANGUL_POC_ESCAPE, $09, $1f
charmap "컥", HANGUL_POC_ESCAPE, $09, $20
charmap "컨", HANGUL_POC_ESCAPE, $09, $21
charmap "컫", HANGUL_POC_ESCAPE, $09, $22
charmap "컬", HANGUL_POC_ESCAPE, $09, $23
charmap "컴", HANGUL_POC_ESCAPE, $09, $24
charmap "컵", HANGUL_POC_ESCAPE, $09, $25
charmap "컷", HANGUL_POC_ESCAPE, $09, $26
charmap "컸", HANGUL_POC_ESCAPE, $09, $27
charmap "컹", HANGUL_POC_ESCAPE, $09, $28
charmap "케", HANGUL_POC_ESCAPE, $09, $29
charmap "켁", HANGUL_POC_ESCAPE, $09, $2a
charmap "켄", HANGUL_POC_ESCAPE, $09, $2b
charmap "켈", HANGUL_POC_ESCAPE, $09, $2c
charmap "켐", HANGUL_POC_ESCAPE, $09, $2d
charmap "켑", HANGUL_POC_ESCAPE, $09, $2e
charmap "켓", HANGUL_POC_ESCAPE, $09, $2f
charmap "켕", HANGUL_POC_ESCAPE, $09, $30
charmap "켜", HANGUL_POC_ESCAPE, $09, $31
charmap "켠", HANGUL_POC_ESCAPE, $09, $32
charmap "켤", HANGUL_POC_ESCAPE, $09, $33
charmap "켬", HANGUL_POC_ESCAPE, $09, $34
charmap "켭", HANGUL_POC_ESCAPE, $09, $35
charmap "켯", HANGUL_POC_ESCAPE, $09, $36
charmap "켰", HANGUL_POC_ESCAPE, $09, $37
charmap "켱", HANGUL_POC_ESCAPE, $09, $38
charmap "켸", HANGUL_POC_ESCAPE, $09, $39
charmap "코", HANGUL_POC_ESCAPE, $09, $3a
charmap "콕", HANGUL_POC_ESCAPE, $09, $3b
charmap "콘", HANGUL_POC_ESCAPE, $09, $3c
charmap "콜", HANGUL_POC_ESCAPE, $09, $3d
charmap "콤", HANGUL_POC_ESCAPE, $09, $3e
charmap "콥", HANGUL_POC_ESCAPE, $09, $3f
charmap "콧", HANGUL_POC_ESCAPE, $09, $40
charmap "콩", HANGUL_POC_ESCAPE, $09, $41
charmap "콰", HANGUL_POC_ESCAPE, $09, $42
charmap "콱", HANGUL_POC_ESCAPE, $09, $43
charmap "콴", HANGUL_POC_ESCAPE, $09, $44
charmap "콸", HANGUL_POC_ESCAPE, $09, $45
charmap "쾀", HANGUL_POC_ESCAPE, $09, $46
charmap "쾅", HANGUL_POC_ESCAPE, $09, $47
charmap "쾌", HANGUL_POC_ESCAPE, $09, $48
charmap "쾡", HANGUL_POC_ESCAPE, $09, $49
charmap "쾨", HANGUL_POC_ESCAPE, $09, $4a
charmap "쾰", HANGUL_POC_ESCAPE, $09, $4b
charmap "쿄", HANGUL_POC_ESCAPE, $09, $4c
charmap "쿠", HANGUL_POC_ESCAPE, $09, $4d
charmap "쿡", HANGUL_POC_ESCAPE, $09, $4e
charmap "쿤", HANGUL_POC_ESCAPE, $09, $4f
charmap "쿨", HANGUL_POC_ESCAPE, $09, $60
charmap "쿰", HANGUL_POC_ESCAPE, $09, $61
charmap "쿱", HANGUL_POC_ESCAPE, $09, $62
charmap "쿳", HANGUL_POC_ESCAPE, $09, $63
charmap "쿵", HANGUL_POC_ESCAPE, $09, $64
charmap "쿼", HANGUL_POC_ESCAPE, $09, $65
charmap "퀀", HANGUL_POC_ESCAPE, $09, $66
charmap "퀄", HANGUL_POC_ESCAPE, $09, $67
charmap "퀑", HANGUL_POC_ESCAPE, $09, $68
charmap "퀘", HANGUL_POC_ESCAPE, $09, $69
charmap "퀭", HANGUL_POC_ESCAPE, $09, $6a
charmap "퀴", HANGUL_POC_ESCAPE, $09, $6b
charmap "퀵", HANGUL_POC_ESCAPE, $09, $6c
charmap "퀸", HANGUL_POC_ESCAPE, $09, $6d
charmap "퀼", HANGUL_POC_ESCAPE, $09, $6e
charmap "큄", HANGUL_POC_ESCAPE, $09, $71
charmap "큅", HANGUL_POC_ESCAPE, $09, $72
charmap "큇", HANGUL_POC_ESCAPE, $09, $73
charmap "큉", HANGUL_POC_ESCAPE, $09, $74
charmap "큐", HANGUL_POC_ESCAPE, $09, $75
charmap "큔", HANGUL_POC_ESCAPE, $09, $76
charmap "큘", HANGUL_POC_ESCAPE, $09, $77
charmap "큠", HANGUL_POC_ESCAPE, $09, $78
charmap "크", HANGUL_POC_ESCAPE, $09, $79
charmap "큭", HANGUL_POC_ESCAPE, $09, $7a
charmap "큰", HANGUL_POC_ESCAPE, $09, $7b
charmap "클", HANGUL_POC_ESCAPE, $09, $7c
charmap "큼", HANGUL_POC_ESCAPE, $09, $7d
charmap "큽", HANGUL_POC_ESCAPE, $09, $7e
charmap "킁", HANGUL_POC_ESCAPE, $09, $7f
charmap "키", HANGUL_POC_ESCAPE, $09, $80
charmap "킥", HANGUL_POC_ESCAPE, $09, $81
charmap "킨", HANGUL_POC_ESCAPE, $09, $82
charmap "킬", HANGUL_POC_ESCAPE, $09, $83
charmap "킴", HANGUL_POC_ESCAPE, $09, $84
charmap "킵", HANGUL_POC_ESCAPE, $09, $85
charmap "킷", HANGUL_POC_ESCAPE, $09, $86
charmap "킹", HANGUL_POC_ESCAPE, $09, $87
charmap "타", HANGUL_POC_ESCAPE, $09, $88
charmap "탁", HANGUL_POC_ESCAPE, $09, $89
charmap "탄", HANGUL_POC_ESCAPE, $09, $8a
charmap "탈", HANGUL_POC_ESCAPE, $09, $8b
charmap "탉", HANGUL_POC_ESCAPE, $09, $8c
charmap "탐", HANGUL_POC_ESCAPE, $09, $8d
charmap "탑", HANGUL_POC_ESCAPE, $09, $8e
charmap "탓", HANGUL_POC_ESCAPE, $09, $8f
charmap "탔", HANGUL_POC_ESCAPE, $09, $90
charmap "탕", HANGUL_POC_ESCAPE, $09, $91
charmap "태", HANGUL_POC_ESCAPE, $09, $92
charmap "택", HANGUL_POC_ESCAPE, $09, $93
charmap "탠", HANGUL_POC_ESCAPE, $09, $94
charmap "탤", HANGUL_POC_ESCAPE, $09, $95
charmap "탬", HANGUL_POC_ESCAPE, $09, $96
charmap "탭", HANGUL_POC_ESCAPE, $09, $97
charmap "탯", HANGUL_POC_ESCAPE, $09, $98
charmap "탰", HANGUL_POC_ESCAPE, $09, $99
charmap "탱", HANGUL_POC_ESCAPE, $09, $9a
charmap "탸", HANGUL_POC_ESCAPE, $09, $9b
charmap "턍", HANGUL_POC_ESCAPE, $09, $9c
charmap "터", HANGUL_POC_ESCAPE, $09, $9d
charmap "턱", HANGUL_POC_ESCAPE, $09, $9e
charmap "턴", HANGUL_POC_ESCAPE, $09, $9f
charmap "털", HANGUL_POC_ESCAPE, $09, $a0
charmap "턺", HANGUL_POC_ESCAPE, $09, $a1
charmap "텀", HANGUL_POC_ESCAPE, $09, $a2
charmap "텁", HANGUL_POC_ESCAPE, $09, $a3
charmap "텃", HANGUL_POC_ESCAPE, $09, $a4
charmap "텄", HANGUL_POC_ESCAPE, $09, $a5
charmap "텅", HANGUL_POC_ESCAPE, $09, $a6
charmap "테", HANGUL_POC_ESCAPE, $09, $a7
charmap "텍", HANGUL_POC_ESCAPE, $09, $a8
charmap "텐", HANGUL_POC_ESCAPE, $09, $a9
charmap "텔", HANGUL_POC_ESCAPE, $09, $aa
charmap "템", HANGUL_POC_ESCAPE, $09, $ab
charmap "텝", HANGUL_POC_ESCAPE, $09, $ac
charmap "텟", HANGUL_POC_ESCAPE, $09, $ad
charmap "텡", HANGUL_POC_ESCAPE, $09, $ae
charmap "텨", HANGUL_POC_ESCAPE, $09, $af
charmap "텬", HANGUL_POC_ESCAPE, $09, $b0
charmap "텼", HANGUL_POC_ESCAPE, $09, $b1
charmap "톄", HANGUL_POC_ESCAPE, $09, $b2
charmap "톈", HANGUL_POC_ESCAPE, $09, $b3
charmap "토", HANGUL_POC_ESCAPE, $09, $b4
charmap "톡", HANGUL_POC_ESCAPE, $09, $b5
charmap "톤", HANGUL_POC_ESCAPE, $09, $b6
charmap "톨", HANGUL_POC_ESCAPE, $09, $b7
charmap "톰", HANGUL_POC_ESCAPE, $09, $b8
charmap "톱", HANGUL_POC_ESCAPE, $09, $b9
charmap "톳", HANGUL_POC_ESCAPE, $09, $ba
charmap "통", HANGUL_POC_ESCAPE, $09, $bb
charmap "톺", HANGUL_POC_ESCAPE, $09, $bc
charmap "톼", HANGUL_POC_ESCAPE, $09, $bd
charmap "퇀", HANGUL_POC_ESCAPE, $09, $be
charmap "퇘", HANGUL_POC_ESCAPE, $09, $bf
charmap "퇴", HANGUL_POC_ESCAPE, $09, $c0
charmap "퇸", HANGUL_POC_ESCAPE, $09, $c1
charmap "툇", HANGUL_POC_ESCAPE, $09, $c2
charmap "툉", HANGUL_POC_ESCAPE, $09, $c3
charmap "툐", HANGUL_POC_ESCAPE, $09, $c4
charmap "투", HANGUL_POC_ESCAPE, $09, $c5
charmap "툭", HANGUL_POC_ESCAPE, $09, $c6
charmap "툰", HANGUL_POC_ESCAPE, $09, $c7
charmap "툴", HANGUL_POC_ESCAPE, $09, $c8
charmap "툼", HANGUL_POC_ESCAPE, $09, $c9
charmap "툽", HANGUL_POC_ESCAPE, $09, $ca
charmap "툿", HANGUL_POC_ESCAPE, $09, $cb
charmap "퉁", HANGUL_POC_ESCAPE, $09, $cc
charmap "퉈", HANGUL_POC_ESCAPE, $09, $cd
charmap "퉜", HANGUL_POC_ESCAPE, $09, $ce
charmap "퉤", HANGUL_POC_ESCAPE, $09, $d1
charmap "튀", HANGUL_POC_ESCAPE, $09, $d2
charmap "튁", HANGUL_POC_ESCAPE, $09, $d3
charmap "튄", HANGUL_POC_ESCAPE, $09, $d4
charmap "튈", HANGUL_POC_ESCAPE, $09, $d5
charmap "튐", HANGUL_POC_ESCAPE, $09, $d6
charmap "튑", HANGUL_POC_ESCAPE, $09, $d7
charmap "튕", HANGUL_POC_ESCAPE, $09, $d8
charmap "튜", HANGUL_POC_ESCAPE, $09, $d9
charmap "튠", HANGUL_POC_ESCAPE, $09, $da
charmap "튤", HANGUL_POC_ESCAPE, $09, $db
charmap "튬", HANGUL_POC_ESCAPE, $09, $dc
charmap "튱", HANGUL_POC_ESCAPE, $09, $dd
charmap "트", HANGUL_POC_ESCAPE, $09, $de
charmap "특", HANGUL_POC_ESCAPE, $09, $df
charmap "튼", HANGUL_POC_ESCAPE, $09, $e0
charmap "튿", HANGUL_POC_ESCAPE, $09, $e1
charmap "틀", HANGUL_POC_ESCAPE, $09, $e2
charmap "틂", HANGUL_POC_ESCAPE, $09, $e3
charmap "틈", HANGUL_POC_ESCAPE, $09, $e4
charmap "틉", HANGUL_POC_ESCAPE, $09, $e5
charmap "틋", HANGUL_POC_ESCAPE, $09, $e6
charmap "틔", HANGUL_POC_ESCAPE, $09, $e7
charmap "틘", HANGUL_POC_ESCAPE, $09, $e8
charmap "틜", HANGUL_POC_ESCAPE, $09, $e9
charmap "틤", HANGUL_POC_ESCAPE, $09, $ea
charmap "틥", HANGUL_POC_ESCAPE, $09, $eb
charmap "티", HANGUL_POC_ESCAPE, $09, $ec
charmap "틱", HANGUL_POC_ESCAPE, $09, $ed
charmap "틴", HANGUL_POC_ESCAPE, $09, $ee
charmap "틸", HANGUL_POC_ESCAPE, $09, $ef
charmap "팀", HANGUL_POC_ESCAPE, $09, $f0
charmap "팁", HANGUL_POC_ESCAPE, $09, $f1
charmap "팃", HANGUL_POC_ESCAPE, $09, $f2
charmap "팅", HANGUL_POC_ESCAPE, $09, $f3
charmap "파", HANGUL_POC_ESCAPE, $09, $f4
charmap "팍", HANGUL_POC_ESCAPE, $09, $f5
charmap "팎", HANGUL_POC_ESCAPE, $09, $f6
charmap "판", HANGUL_POC_ESCAPE, $09, $f7
charmap "팔", HANGUL_POC_ESCAPE, $09, $f8
charmap "팖", HANGUL_POC_ESCAPE, $09, $f9
charmap "팜", HANGUL_POC_ESCAPE, $09, $fa
charmap "팝", HANGUL_POC_ESCAPE, $09, $fb
charmap "팟", HANGUL_POC_ESCAPE, $09, $fc
charmap "팠", HANGUL_POC_ESCAPE, $09, $fd
charmap "팡", HANGUL_POC_ESCAPE, $09, $fe
charmap "팥", HANGUL_POC_ESCAPE, $09, $ff
charmap "패", HANGUL_POC_ESCAPE, $0a, $00
charmap "팩", HANGUL_POC_ESCAPE, $0a, $01
charmap "팬", HANGUL_POC_ESCAPE, $0a, $02
charmap "팰", HANGUL_POC_ESCAPE, $0a, $03
charmap "팸", HANGUL_POC_ESCAPE, $0a, $04
charmap "팹", HANGUL_POC_ESCAPE, $0a, $05
charmap "팻", HANGUL_POC_ESCAPE, $0a, $06
charmap "팼", HANGUL_POC_ESCAPE, $0a, $07
charmap "팽", HANGUL_POC_ESCAPE, $0a, $08
charmap "퍄", HANGUL_POC_ESCAPE, $0a, $09
charmap "퍅", HANGUL_POC_ESCAPE, $0a, $0a
charmap "퍼", HANGUL_POC_ESCAPE, $0a, $0b
charmap "퍽", HANGUL_POC_ESCAPE, $0a, $0c
charmap "펀", HANGUL_POC_ESCAPE, $0a, $0d
charmap "펄", HANGUL_POC_ESCAPE, $0a, $0e
charmap "펌", HANGUL_POC_ESCAPE, $0a, $0f
charmap "펍", HANGUL_POC_ESCAPE, $0a, $10
charmap "펏", HANGUL_POC_ESCAPE, $0a, $11
charmap "펐", HANGUL_POC_ESCAPE, $0a, $12
charmap "펑", HANGUL_POC_ESCAPE, $0a, $13
charmap "페", HANGUL_POC_ESCAPE, $0a, $14
charmap "펙", HANGUL_POC_ESCAPE, $0a, $15
charmap "펜", HANGUL_POC_ESCAPE, $0a, $16
charmap "펠", HANGUL_POC_ESCAPE, $0a, $17
charmap "펨", HANGUL_POC_ESCAPE, $0a, $18
charmap "펩", HANGUL_POC_ESCAPE, $0a, $19
charmap "펫", HANGUL_POC_ESCAPE, $0a, $1a
charmap "펭", HANGUL_POC_ESCAPE, $0a, $1b
charmap "펴", HANGUL_POC_ESCAPE, $0a, $1c
charmap "편", HANGUL_POC_ESCAPE, $0a, $1d
charmap "펼", HANGUL_POC_ESCAPE, $0a, $1e
charmap "폄", HANGUL_POC_ESCAPE, $0a, $1f
charmap "폅", HANGUL_POC_ESCAPE, $0a, $20
charmap "폈", HANGUL_POC_ESCAPE, $0a, $21
charmap "평", HANGUL_POC_ESCAPE, $0a, $22
charmap "폐", HANGUL_POC_ESCAPE, $0a, $23
charmap "폘", HANGUL_POC_ESCAPE, $0a, $24
charmap "폡", HANGUL_POC_ESCAPE, $0a, $25
charmap "폣", HANGUL_POC_ESCAPE, $0a, $26
charmap "포", HANGUL_POC_ESCAPE, $0a, $27
charmap "폭", HANGUL_POC_ESCAPE, $0a, $28
charmap "폰", HANGUL_POC_ESCAPE, $0a, $29
charmap "폴", HANGUL_POC_ESCAPE, $0a, $2a
charmap "폼", HANGUL_POC_ESCAPE, $0a, $2b
charmap "폽", HANGUL_POC_ESCAPE, $0a, $2c
charmap "폿", HANGUL_POC_ESCAPE, $0a, $2d
charmap "퐁", HANGUL_POC_ESCAPE, $0a, $2e
charmap "퐈", HANGUL_POC_ESCAPE, $0a, $31
charmap "퐝", HANGUL_POC_ESCAPE, $0a, $32
charmap "푀", HANGUL_POC_ESCAPE, $0a, $33
charmap "푄", HANGUL_POC_ESCAPE, $0a, $34
charmap "표", HANGUL_POC_ESCAPE, $0a, $35
charmap "푠", HANGUL_POC_ESCAPE, $0a, $36
charmap "푤", HANGUL_POC_ESCAPE, $0a, $37
charmap "푭", HANGUL_POC_ESCAPE, $0a, $38
charmap "푯", HANGUL_POC_ESCAPE, $0a, $39
charmap "푸", HANGUL_POC_ESCAPE, $0a, $3a
charmap "푹", HANGUL_POC_ESCAPE, $0a, $3b
charmap "푼", HANGUL_POC_ESCAPE, $0a, $3c
charmap "푿", HANGUL_POC_ESCAPE, $0a, $3d
charmap "풀", HANGUL_POC_ESCAPE, $0a, $3e
charmap "풂", HANGUL_POC_ESCAPE, $0a, $3f
charmap "품", HANGUL_POC_ESCAPE, $0a, $40
charmap "풉", HANGUL_POC_ESCAPE, $0a, $41
charmap "풋", HANGUL_POC_ESCAPE, $0a, $42
charmap "풍", HANGUL_POC_ESCAPE, $0a, $43
charmap "풔", HANGUL_POC_ESCAPE, $0a, $44
charmap "풩", HANGUL_POC_ESCAPE, $0a, $45
charmap "퓌", HANGUL_POC_ESCAPE, $0a, $46
charmap "퓐", HANGUL_POC_ESCAPE, $0a, $47
charmap "퓔", HANGUL_POC_ESCAPE, $0a, $48
charmap "퓜", HANGUL_POC_ESCAPE, $0a, $49
charmap "퓟", HANGUL_POC_ESCAPE, $0a, $4a
charmap "퓨", HANGUL_POC_ESCAPE, $0a, $4b
charmap "퓬", HANGUL_POC_ESCAPE, $0a, $4c
charmap "퓰", HANGUL_POC_ESCAPE, $0a, $4d
charmap "퓸", HANGUL_POC_ESCAPE, $0a, $4e
charmap "퓻", HANGUL_POC_ESCAPE, $0a, $4f
charmap "퓽", HANGUL_POC_ESCAPE, $0a, $60
charmap "프", HANGUL_POC_ESCAPE, $0a, $61
charmap "픈", HANGUL_POC_ESCAPE, $0a, $62
charmap "플", HANGUL_POC_ESCAPE, $0a, $63
charmap "픔", HANGUL_POC_ESCAPE, $0a, $64
charmap "픕", HANGUL_POC_ESCAPE, $0a, $65
charmap "픗", HANGUL_POC_ESCAPE, $0a, $66
charmap "피", HANGUL_POC_ESCAPE, $0a, $67
charmap "픽", HANGUL_POC_ESCAPE, $0a, $68
charmap "핀", HANGUL_POC_ESCAPE, $0a, $69
charmap "필", HANGUL_POC_ESCAPE, $0a, $6a
charmap "핌", HANGUL_POC_ESCAPE, $0a, $6b
charmap "핍", HANGUL_POC_ESCAPE, $0a, $6c
charmap "핏", HANGUL_POC_ESCAPE, $0a, $6d
charmap "핑", HANGUL_POC_ESCAPE, $0a, $6e
charmap "하", HANGUL_POC_ESCAPE, $0a, $6f
charmap "학", HANGUL_POC_ESCAPE, $0a, $70
charmap "할", HANGUL_POC_ESCAPE, $0a, $72
charmap "핥", HANGUL_POC_ESCAPE, $0a, $73
charmap "함", HANGUL_POC_ESCAPE, $0a, $74
charmap "합", HANGUL_POC_ESCAPE, $0a, $75
charmap "핫", HANGUL_POC_ESCAPE, $0a, $76
charmap "항", HANGUL_POC_ESCAPE, $0a, $77
charmap "해", HANGUL_POC_ESCAPE, $0a, $78
charmap "핵", HANGUL_POC_ESCAPE, $0a, $79
charmap "핸", HANGUL_POC_ESCAPE, $0a, $7a
charmap "핼", HANGUL_POC_ESCAPE, $0a, $7b
charmap "햄", HANGUL_POC_ESCAPE, $0a, $7c
charmap "햅", HANGUL_POC_ESCAPE, $0a, $7d
charmap "햇", HANGUL_POC_ESCAPE, $0a, $7e
charmap "했", HANGUL_POC_ESCAPE, $0a, $7f
charmap "행", HANGUL_POC_ESCAPE, $0a, $80
charmap "햐", HANGUL_POC_ESCAPE, $0a, $81
charmap "향", HANGUL_POC_ESCAPE, $0a, $82
charmap "허", HANGUL_POC_ESCAPE, $0a, $83
charmap "헉", HANGUL_POC_ESCAPE, $0a, $84
charmap "헌", HANGUL_POC_ESCAPE, $0a, $85
charmap "헐", HANGUL_POC_ESCAPE, $0a, $86
charmap "헒", HANGUL_POC_ESCAPE, $0a, $87
charmap "험", HANGUL_POC_ESCAPE, $0a, $88
charmap "헙", HANGUL_POC_ESCAPE, $0a, $89
charmap "헛", HANGUL_POC_ESCAPE, $0a, $8a
charmap "헝", HANGUL_POC_ESCAPE, $0a, $8b
charmap "헤", HANGUL_POC_ESCAPE, $0a, $8c
charmap "헥", HANGUL_POC_ESCAPE, $0a, $8d
charmap "헨", HANGUL_POC_ESCAPE, $0a, $8e
charmap "헬", HANGUL_POC_ESCAPE, $0a, $8f
charmap "헴", HANGUL_POC_ESCAPE, $0a, $90
charmap "헵", HANGUL_POC_ESCAPE, $0a, $91
charmap "헷", HANGUL_POC_ESCAPE, $0a, $92
charmap "헹", HANGUL_POC_ESCAPE, $0a, $93
charmap "혀", HANGUL_POC_ESCAPE, $0a, $94
charmap "혁", HANGUL_POC_ESCAPE, $0a, $95
charmap "현", HANGUL_POC_ESCAPE, $0a, $96
charmap "혈", HANGUL_POC_ESCAPE, $0a, $97
charmap "혐", HANGUL_POC_ESCAPE, $0a, $98
charmap "협", HANGUL_POC_ESCAPE, $0a, $99
charmap "혓", HANGUL_POC_ESCAPE, $0a, $9a
charmap "혔", HANGUL_POC_ESCAPE, $0a, $9b
charmap "형", HANGUL_POC_ESCAPE, $0a, $9c
charmap "혜", HANGUL_POC_ESCAPE, $0a, $9d
charmap "혠", HANGUL_POC_ESCAPE, $0a, $9e
charmap "혤", HANGUL_POC_ESCAPE, $0a, $a1
charmap "혭", HANGUL_POC_ESCAPE, $0a, $a2
charmap "호", HANGUL_POC_ESCAPE, $0a, $a3
charmap "혹", HANGUL_POC_ESCAPE, $0a, $a4
charmap "혼", HANGUL_POC_ESCAPE, $0a, $a5
charmap "홀", HANGUL_POC_ESCAPE, $0a, $a6
charmap "홅", HANGUL_POC_ESCAPE, $0a, $a7
charmap "홈", HANGUL_POC_ESCAPE, $0a, $a8
charmap "홉", HANGUL_POC_ESCAPE, $0a, $a9
charmap "홋", HANGUL_POC_ESCAPE, $0a, $aa
charmap "홍", HANGUL_POC_ESCAPE, $0a, $ab
charmap "홑", HANGUL_POC_ESCAPE, $0a, $ac
charmap "화", HANGUL_POC_ESCAPE, $0a, $ad
charmap "확", HANGUL_POC_ESCAPE, $0a, $ae
charmap "환", HANGUL_POC_ESCAPE, $0a, $af
charmap "활", HANGUL_POC_ESCAPE, $0a, $b0
charmap "홧", HANGUL_POC_ESCAPE, $0a, $b1
charmap "황", HANGUL_POC_ESCAPE, $0a, $b2
charmap "홰", HANGUL_POC_ESCAPE, $0a, $b3
charmap "홱", HANGUL_POC_ESCAPE, $0a, $b4
charmap "홴", HANGUL_POC_ESCAPE, $0a, $b5
charmap "횃", HANGUL_POC_ESCAPE, $0a, $b6
charmap "횅", HANGUL_POC_ESCAPE, $0a, $b7
charmap "회", HANGUL_POC_ESCAPE, $0a, $b8
charmap "획", HANGUL_POC_ESCAPE, $0a, $b9
charmap "횐", HANGUL_POC_ESCAPE, $0a, $ba
charmap "횔", HANGUL_POC_ESCAPE, $0a, $bb
charmap "횝", HANGUL_POC_ESCAPE, $0a, $bc
charmap "횟", HANGUL_POC_ESCAPE, $0a, $bd
charmap "횡", HANGUL_POC_ESCAPE, $0a, $be
charmap "효", HANGUL_POC_ESCAPE, $0a, $bf
charmap "횬", HANGUL_POC_ESCAPE, $0a, $c0
charmap "횰", HANGUL_POC_ESCAPE, $0a, $c1
charmap "횹", HANGUL_POC_ESCAPE, $0a, $c2
charmap "횻", HANGUL_POC_ESCAPE, $0a, $c3
charmap "후", HANGUL_POC_ESCAPE, $0a, $c4
charmap "훅", HANGUL_POC_ESCAPE, $0a, $c5
charmap "훈", HANGUL_POC_ESCAPE, $0a, $c6
charmap "훌", HANGUL_POC_ESCAPE, $0a, $c7
charmap "훑", HANGUL_POC_ESCAPE, $0a, $c8
charmap "훔", HANGUL_POC_ESCAPE, $0a, $c9
charmap "훗", HANGUL_POC_ESCAPE, $0a, $ca
charmap "훙", HANGUL_POC_ESCAPE, $0a, $cb
charmap "훠", HANGUL_POC_ESCAPE, $0a, $cc
charmap "훤", HANGUL_POC_ESCAPE, $0a, $cd
charmap "훨", HANGUL_POC_ESCAPE, $0a, $ce
charmap "훰", HANGUL_POC_ESCAPE, $0a, $cf
charmap "훵", HANGUL_POC_ESCAPE, $0a, $d0
charmap "훼", HANGUL_POC_ESCAPE, $0a, $d1
charmap "훽", HANGUL_POC_ESCAPE, $0a, $d2
charmap "휀", HANGUL_POC_ESCAPE, $0a, $d3
charmap "휄", HANGUL_POC_ESCAPE, $0a, $d4
charmap "휑", HANGUL_POC_ESCAPE, $0a, $d5
charmap "휘", HANGUL_POC_ESCAPE, $0a, $d6
charmap "휙", HANGUL_POC_ESCAPE, $0a, $d7
charmap "휜", HANGUL_POC_ESCAPE, $0a, $d8
charmap "휠", HANGUL_POC_ESCAPE, $0a, $d9
charmap "휨", HANGUL_POC_ESCAPE, $0a, $da
charmap "휩", HANGUL_POC_ESCAPE, $0a, $db
charmap "휫", HANGUL_POC_ESCAPE, $0a, $dc
charmap "휭", HANGUL_POC_ESCAPE, $0a, $dd
charmap "휴", HANGUL_POC_ESCAPE, $0a, $de
charmap "휵", HANGUL_POC_ESCAPE, $0a, $df
charmap "휸", HANGUL_POC_ESCAPE, $0a, $e0
charmap "휼", HANGUL_POC_ESCAPE, $0a, $e1
charmap "흄", HANGUL_POC_ESCAPE, $0a, $e2
charmap "흇", HANGUL_POC_ESCAPE, $0a, $e3
charmap "흉", HANGUL_POC_ESCAPE, $0a, $e4
charmap "흐", HANGUL_POC_ESCAPE, $0a, $e5
charmap "흑", HANGUL_POC_ESCAPE, $0a, $e6
charmap "흔", HANGUL_POC_ESCAPE, $0a, $e7
charmap "흖", HANGUL_POC_ESCAPE, $0a, $e8
charmap "흗", HANGUL_POC_ESCAPE, $0a, $e9
charmap "흘", HANGUL_POC_ESCAPE, $0a, $ea
charmap "흙", HANGUL_POC_ESCAPE, $0a, $eb
charmap "흠", HANGUL_POC_ESCAPE, $0a, $ec
charmap "흡", HANGUL_POC_ESCAPE, $0a, $ed
charmap "흣", HANGUL_POC_ESCAPE, $0a, $ee
charmap "흥", HANGUL_POC_ESCAPE, $0a, $ef
charmap "흩", HANGUL_POC_ESCAPE, $0a, $f0
charmap "희", HANGUL_POC_ESCAPE, $0a, $f1
charmap "흰", HANGUL_POC_ESCAPE, $0a, $f2
charmap "흴", HANGUL_POC_ESCAPE, $0a, $f3
charmap "흼", HANGUL_POC_ESCAPE, $0a, $f4
charmap "흽", HANGUL_POC_ESCAPE, $0a, $f5
charmap "힁", HANGUL_POC_ESCAPE, $0a, $f6
charmap "히", HANGUL_POC_ESCAPE, $0a, $f7
charmap "힉", HANGUL_POC_ESCAPE, $0a, $f8
charmap "힌", HANGUL_POC_ESCAPE, $0a, $f9
charmap "힐", HANGUL_POC_ESCAPE, $0a, $fa
charmap "힘", HANGUL_POC_ESCAPE, $0a, $fb
charmap "힙", HANGUL_POC_ESCAPE, $0a, $fc
charmap "힛", HANGUL_POC_ESCAPE, $0a, $fd
charmap "힝", HANGUL_POC_ESCAPE, $0a, $fe
charmap "ㄱ", HANGUL_POC_ESCAPE, $0b, $00
charmap "ㄴ", HANGUL_POC_ESCAPE, $0b, $01
charmap "ㄷ", HANGUL_POC_ESCAPE, $0b, $02
charmap "ㄹ", HANGUL_POC_ESCAPE, $0b, $03
charmap "ㅁ", HANGUL_POC_ESCAPE, $0b, $04
charmap "ㅂ", HANGUL_POC_ESCAPE, $0b, $05
charmap "ㅅ", HANGUL_POC_ESCAPE, $0b, $06
charmap "ㅇ", HANGUL_POC_ESCAPE, $0b, $07
charmap "ㅈ", HANGUL_POC_ESCAPE, $0b, $08
charmap "ㅊ", HANGUL_POC_ESCAPE, $0b, $09
charmap "ㅋ", HANGUL_POC_ESCAPE, $0b, $0a
charmap "ㅌ", HANGUL_POC_ESCAPE, $0b, $0b
charmap "ㅍ", HANGUL_POC_ESCAPE, $0b, $0c
charmap "ㅎ", HANGUL_POC_ESCAPE, $0b, $0d
charmap "ㄲ", HANGUL_POC_ESCAPE, $0b, $0e
charmap "ㄸ", HANGUL_POC_ESCAPE, $0b, $0f
charmap "ㅃ", HANGUL_POC_ESCAPE, $0b, $10
charmap "ㅆ", HANGUL_POC_ESCAPE, $0b, $11
charmap "ㅉ", HANGUL_POC_ESCAPE, $0b, $12
charmap "ㅏ", HANGUL_POC_ESCAPE, $0b, $20
charmap "ㅑ", HANGUL_POC_ESCAPE, $0b, $21
charmap "ㅓ", HANGUL_POC_ESCAPE, $0b, $22
charmap "ㅕ", HANGUL_POC_ESCAPE, $0b, $23
charmap "ㅗ", HANGUL_POC_ESCAPE, $0b, $24
charmap "ㅛ", HANGUL_POC_ESCAPE, $0b, $25
charmap "ㅜ", HANGUL_POC_ESCAPE, $0b, $26
charmap "ㅠ", HANGUL_POC_ESCAPE, $0b, $27
charmap "ㅡ", HANGUL_POC_ESCAPE, $0b, $28
charmap "ㅣ", HANGUL_POC_ESCAPE, $0b, $29
charmap "ㅐ", HANGUL_POC_ESCAPE, $0b, $2a
charmap "ㅒ", HANGUL_POC_ESCAPE, $0b, $2b
charmap "ㅔ", HANGUL_POC_ESCAPE, $0b, $2c
charmap "ㅖ", HANGUL_POC_ESCAPE, $0b, $2d
charmap "ㅘ", HANGUL_POC_ESCAPE, $0b, $2e
charmap "ㅙ", HANGUL_POC_ESCAPE, $0b, $2f
charmap "ㅚ", HANGUL_POC_ESCAPE, $0b, $30
charmap "ㅝ", HANGUL_POC_ESCAPE, $0b, $31
charmap "ㅞ", HANGUL_POC_ESCAPE, $0b, $32
charmap "ㅟ", HANGUL_POC_ESCAPE, $0b, $33
charmap "ㅢ", HANGUL_POC_ESCAPE, $0b, $34
